"""contractgen — 読み取り専用の契約（C#）を、単位定義の interface から機械的に作る（V2-1）。

    python harness/contractgen.py --project falling-blocks --interface <単位定義か interface の JSON> --out <dir>

docs/design/v2_contract_foundry.md §3。誰も C# を手書きしない。総監督は生成物を見ず、入力の JSON と
生成物の sha256（contract.lock.json）だけを扱う（ADR-002 の防壁①）。

**型の 2 分類**（§3.1。kind と members から機械的に決まる）
- データ型：enum と、「コンストラクタ 1 つ＋そのすべての引数に同名（先頭を大文字）・同型の property」だけの struct。
  C# の実装そのものを出す（値の等価性つき。性質テストが `after.ActiveMino == ...` と比べるため）。実装役は書かない
- 振る舞いの型：それ以外（class、method を持つ struct）。`I<型名>` の interface を出す。実装役が
  `class 型名 : I型名` を書く。interface に書けないもの（コンストラクタ・static・const・field）は探針で縛る

**契約の探針**（§3.3）：テストプロジェクトに置く、実行しないクラス。振る舞いの型のコンストラクタ・メンバーを
宣言どおりの型で呼び、`I<型名>` を実装していることを確かめる。形が違えばコンパイルで落ちる。
シグネチャを文字列で照合しない（v1 の pipeline.py の静的な門が、whitelist の外のファイルを見られずに誤爆した）。
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import exitcode
import project
import testgen
import unit_schema

HEADER = "// <auto-generated> contractgen が単位定義の interface から作った契約。手で書き換えない。</auto-generated>"
CONTRACTS_DIR = "Contracts"
PROBE_NAMESPACE = testgen.TEST_NAMESPACE.rsplit(".", 1)[0] + ".Contracts"
LOCK_NAME = "contract.lock.json"
_WORD_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*")


class ContractError(Exception):
    pass


def _pascal(name):
    return name[:1].upper() + name[1:]


def _members(t, kind):
    return [m for m in t.get("members", []) if m["kind"] == kind]


def check(interface):
    """interface の形の検査。問題の一覧（空なら合格）。単位定義のスキーマ門と同じ語彙で見る。"""
    problems, names = [], set()
    types = interface.get("types") if isinstance(interface, dict) else None
    if not isinstance(types, list) or not types:
        return ["interface.types は 1 つ以上の型の列にしてください"]
    for i, t in enumerate(types):
        where = f"interface.types[{i}]"
        if not isinstance(t, dict) or not unit_schema.IDENT_RE.match(str(t.get("name", ""))) \
                or t.get("kind") not in unit_schema.TYPE_KINDS:
            problems.append(f"{where}: name は識別子、kind は {sorted(unit_schema.TYPE_KINDS)} のどれか")
            continue
        if t["name"] in names:
            problems.append(f"{where}: 型 {t['name']} が重複しています")
        names.add(t["name"])
        if t["kind"] == "enum":
            if not t.get("values") or not all(unit_schema.IDENT_RE.match(str(v)) for v in t["values"]):
                problems.append(f"{where}: enum の values は識別子の列にしてください")
            continue
        for j, m in enumerate(t.get("members", [])):
            mw = f"{where}.members[{j}]"
            if m.get("kind") not in unit_schema.MEMBER_KINDS or not unit_schema.IDENT_RE.match(str(m.get("name", ""))):
                problems.append(f"{mw}: name は識別子、kind は {sorted(unit_schema.MEMBER_KINDS)} のどれか")
            elif m["kind"] != "ctor" and not unit_schema.TYPE_RE.match(str(m.get("type", ""))):
                problems.append(f"{mw}: type を書いてください")
            for k, p in enumerate(m.get("params", []) or []):
                if not unit_schema.IDENT_RE.match(str(p.get("name", ""))) \
                        or not unit_schema.TYPE_RE.match(str(p.get("type", ""))):
                    problems.append(f"{mw}.params[{k}]: name は識別子、type は型にしてください")
    return problems


def classify(t):
    """"enum" | "data" | "behavior"。"""
    if t["kind"] == "enum":
        return "enum"
    if t["kind"] != "struct":
        return "behavior"
    members = t.get("members", [])
    if any(m["kind"] not in ("ctor", "property") or m.get("static") for m in members):
        return "behavior"
    ctors, props = _members(t, "ctor"), {m["name"]: m["type"] for m in _members(t, "property")}
    if len(ctors) != 1:
        return "behavior"
    params = ctors[0].get("params", [])
    if {_pascal(p["name"]): p["type"] for p in params} != props:
        # コンストラクタと property が一対一に対応しないデータ型は、代入のしかたが一意に決まらない
        raise ContractError(f"struct {t['name']}: コンストラクタの引数と property が一対一に対応しません"
                            f"（引数 {[p['name'] for p in params]}、property {sorted(props)}）")
    return "data"


class _Names:
    """宣言した型の名前を global:: 付きの完全修飾名にする。property の名前が型名と同じでも曖昧にしない。"""

    def __init__(self, interface):
        self.declared = {t["name"] for t in interface["types"]}

    def q(self, type_text):
        def one(m):
            word = m.group(0)
            if word in self.declared:
                return f"global::{testgen.CORE_NAMESPACE}.{word}"
            return f"global::{word}" if word.startswith("System.") else word
        return _WORD_RE.sub(one, type_text)


def _enum(t):
    return [f"    public enum {t['name']}", "    {", f"        {', '.join(t['values'])}", "    }"]


def _data(t, n):
    name, ctor = t["name"], _members(t, "ctor")[0]
    params = ctor.get("params", [])
    props = [(_pascal(p["name"]), n.q(p["type"])) for p in params]
    sig = ", ".join(f"{n.q(p['type'])} {p['name']}" for p in params)
    out = [f"    public readonly struct {name} : global::System.IEquatable<{name}>", "    {",
           f"        public {name}({sig})", "        {"]
    out += [f"            {prop} = {p['name']};" for (prop, _), p in zip(props, params)]
    out += ["        }", ""]
    out += [f"        public {typ} {prop} {{ get; }}" for prop, typ in props]
    eq = "\n            && ".join(f"global::System.Collections.Generic.EqualityComparer<{typ}>.Default"
                                  f".Equals({prop}, other.{prop})" for prop, typ in props) or "true"
    out += ["", f"        public bool Equals({name} other) =>", f"            {eq};",
            f"        public override bool Equals(object obj) => obj is {name} other && Equals(other);",
            "        public override int GetHashCode()", "        {", "            unchecked", "            {",
            "                int h = 17;"]
    out += [f"                h = h * 31 + global::System.Collections.Generic.EqualityComparer<{typ}>.Default"
            f".GetHashCode({prop});" for prop, typ in props]
    out += ["                return h;", "            }", "        }",
            f"        public static bool operator ==({name} a, {name} b) => a.Equals(b);",
            f"        public static bool operator !=({name} a, {name} b) => !a.Equals(b);",
            "    }"]
    return out


def _interface(t, n):
    out = [f"    public interface I{t['name']}", "    {"]
    for m in t.get("members", []):
        if m.get("static") or m["kind"] not in ("property", "method"):
            continue   # interface に書けないものは探針で縛る
        if m["kind"] == "property":
            out.append(f"        {n.q(m['type'])} {m['name']} {{ get; }}")
        else:
            ps = ", ".join(f"{n.q(p['type'])} {p['name']}" for p in m.get("params", []))
            out.append(f"        {n.q(m['type'])} {m['name']}({ps});")
    out.append("    }")
    return out


def _probe(interface, n):
    """振る舞いの型ごとに、宣言どおりの型で呼ぶだけのメソッド。実行しない。"""
    out = [HEADER, "#nullable disable", f"namespace {PROBE_NAMESPACE}", "{",
           "    // 実行しない。コンパイルが通ることが検査（docs/design/v2_contract_foundry.md §3.3）",
           "    internal static class ContractProbe", "    {",
           "        private static void Is<T>(T value) { }", ""]
    for t in interface["types"]:
        if classify(t) != "behavior":
            continue
        typ = n.q(t["name"])
        args = lambda m: ", ".join(f"default({n.q(p['type'])})" for p in m.get("params", []))  # noqa: E731
        body = [f"            {typ} x = default({typ});",
                f"            Is<global::{testgen.CORE_NAMESPACE}.I{t['name']}>(x);"]
        for m in t.get("members", []):
            owner = typ if m.get("static") or m["kind"] == "const" else "x"
            if m["kind"] == "ctor":
                body.append(f"            Is<{typ}>(new {typ}({args(m)}));")
            elif m["kind"] in ("property", "field", "const"):
                body.append(f"            Is<{n.q(m['type'])}>({owner}.{m['name']});")
            elif m["type"] == "void":
                body.append(f"            {owner}.{m['name']}({args(m)});")
            else:
                body.append(f"            Is<{n.q(m['type'])}>({owner}.{m['name']}({args(m)}));")
        out += [f"        private static void {t['name']}Shape()", "        {"] + body + ["        }", ""]
    out[-1:] = ["    }", "}", ""]
    return "\n".join(out)


def generate(interface, impl_dir, test_dir, existing=(), subdir=CONTRACTS_DIR):
    """{リポジトリからの相対パス: C# の本文}。決定論（同じ入力なら同じバイト列）。

    existing：base に既にあるデータ型の名前。生成しない（同じ名前の型が 2 つになってビルドが通らない）。
    形は探針と性質テストのビルドが確かめる。振る舞いの型は、既にあっても I<型名> を生成する。
    subdir：実装側の置き場（impl_dir の下）。"" なら impl_dir の直下。探針は常に test_dir/Contracts。
    """
    problems = check(interface)
    if problems:
        raise ContractError("interface の形が不正です: " + "; ".join(problems))
    n = _Names(interface)
    files, where = {}, f"{impl_dir}/{subdir}" if subdir else impl_dir
    for t in interface["types"]:
        kind = classify(t)
        if kind != "behavior" and t["name"] in existing:
            continue
        body = _enum(t) if kind == "enum" else _data(t, n) if kind == "data" else _interface(t, n)
        name = t["name"] if kind != "behavior" else "I" + t["name"]
        text = "\n".join([HEADER, "#nullable disable", f"namespace {testgen.CORE_NAMESPACE}", "{"] + body + ["}", ""])
        files[f"{where}/{name}.cs"] = text
    files[f"{test_dir}/{CONTRACTS_DIR}/ContractProbe.cs"] = _probe(interface, n)
    return files


def lock(files):
    """生成物の sha256。測定器と門は、これと違う生成物を「書き換えられた」とみなす（§3.4）。"""
    return {rel: hashlib.sha256(text.encode("utf-8")).hexdigest() for rel, text in sorted(files.items())}


def implementer_owned(interface):
    """実装役が書く型（振る舞いの型）の名前。データ型は契約の生成物なので、実装役の仕事から外れる。"""
    return [t["name"] for t in interface["types"] if classify(t) == "behavior"]


def load_interface(path):
    """単位定義（interface を持つ）か、interface そのものの JSON を読む。"""
    d = json.loads(Path(path).read_text(encoding="utf-8"))
    return d["interface"] if isinstance(d, dict) and "interface" in d else d


def main(argv=None):
    ap = argparse.ArgumentParser(description="単位定義の interface から、読み取り専用の契約（C#）を作る")
    ap.add_argument("--project", required=True)
    ap.add_argument("--interface", required=True, help="単位定義か interface の JSON")
    ap.add_argument("--out", required=True, help="書き出し先（リポジトリからの相対パスをそのまま下に作る）")
    args = ap.parse_args(argv)
    proj = project.load(args.project)
    try:
        files = generate(load_interface(args.interface), proj["impl_dir"], proj["test_dir"])
    except ContractError as e:
        print(f"NG: {e}")
        return 1
    out = Path(args.out)
    for rel, text in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))
    (out / LOCK_NAME).write_text(json.dumps(lock(files), ensure_ascii=False, indent=2) + "\n",
                                 encoding="utf-8", newline="\n")
    print(f"書き出し: {len(files)} ファイルと {LOCK_NAME}（{out}）")
    return 0


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(exitcode.normalized(main))
