"""contractgen — 読み取り専用の契約（C#）を、単位定義の interface から機械的に作る（V2-1）。

    python harness/contractgen.py --project falling-blocks --interface <単位定義か interface の JSON> --out <dir>

docs/design/v2_contract_foundry.md §3。誰も C# を手書きしない。総監督は生成物を見ず、入力の JSON と
生成物の sha256（contract.lock.json）だけを扱う（ADR-002 の防壁①）。

**型の 2 分類**（§3.1。kind と members から機械的に決まる）
- データ型：enum と、「コンストラクタ 1 つ＋そのすべての引数に同名（先頭を大文字）・同型の property」だけの struct。
  C# の実装そのものを出す（値の等価性つき。性質テストが `after.ActiveMino == ...` と比べるため）。実装役は書かない
- 振る舞いの型：それ以外（class、method を持つ struct）。`I<型名>` の interface を出す。実装役が
  `class 型名 : I型名` を書く。interface に書けないもの（コンストラクタ・static・const・field）は探針で縛る

**契約の探針**（§3.3）：テストプロジェクトに置く、実行しないクラス。振る舞いの型のコンストラクタ・メンバーを
宣言どおりの型で呼び、`I<型名>` を実装していることを確かめる。形が違えばコンパイルで落ちる。
シグネチャを文字列で照合しない（v1 の pipeline.py の静的な門が、whitelist の外のファイルを見られずに誤爆した）。
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import exitcode
import project
import testgen
import unit_schema

HEADER = "// <auto-generated> contractgen が単位定義の interface から作った契約。手で書き換えない。</auto-generated>"
CONTRACTS_DIR = "Contracts"
PROBE_NAMESPACE = testgen.TEST_NAMESPACE.rsplit(".", 1)[0] + ".Contracts"
LOCK_NAME = "contract.lock.json"
_WORD_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*")


class ContractError(Exception):
    pass


def _pascal(name):
    return name[:1].upper() + name[1:]


def _members(t, kind):
    return [m for m in t.get("members", []) if m["kind"] == kind]


def check(interface):
    """interface の形の検査。問題の一覧（空なら合格）。単位定義のスキーマ門と同じ語彙で見る。"""
    problems, names = [], set()
    types = interface.get("types") if isinstance(interface, dict) else None
    if not isinstance(types, list) or not types:
        return ["interface.types は 1 つ以上の型の列にしてください"]
    for i, t in enumerate(types):
        where = f"interface.types[{i}]"
        if not isinstance(t, dict) or not unit_schema.IDENT_RE.match(str(t.get("name", ""))) \
                or t.get("kind") not in unit_schema.TYPE_KINDS:
            problems.append(f"{where}: name は識別子、kind は {sorted(unit_schema.TYPE_KINDS)} のどれか")
            continue
        if t["name"] in names:
            problems.append(f"{where}: 型 {t['name']} が重複しています")
        names.add(t["name"])
        if t["kind"] == "enum":
            if not t.get("values") or not all(unit_schema.IDENT_RE.match(str(v)) for v in t["values"]):
                problems.append(f"{where}: enum の values は識別子の列にしてください")
            continue
        for j, m in enumerate(t.get("members", [])):
            mw = f"{where}.members[{j}]"
            if m.get("kind") not in unit_schema.MEMBER_KINDS or not unit_schema.IDENT_RE.match(str(m.get("name", ""))):
                problems.append(f"{mw}: name は識別子、kind は {sorted(unit_schema.MEMBER_KINDS)} のどれか")
            elif m["kind"] != "ctor" and not unit_schema.TYPE_RE.match(str(m.get("type", ""))):
                problems.append(f"{mw}: type を書いてください")
            for k, p in enumerate(m.get("params", []) or []):
                if not unit_schema.IDENT_RE.match(str(p.get("name", ""))) \
                        or not unit_schema.TYPE_RE.match(str(p.get("type", ""))):
                    problems.append(f"{mw}.params[{k}]: name は識別子、type は型にしてください")
    return problems


def classify(t):
    """"enum" | "data" | "behavior"。"""
    if t["kind"] == "enum":
        return "enum"
    if t["kind"] != "struct":
        return "behavior"
    members = t.get("members", [])
    if any(m["kind"] not in ("ctor", "property") or m.get("static") for m in members):
        return "behavior"
    ctors, props = _members(t, "ctor"), {m["name"]: m["type"] for m in _members(t, "property")}
    if len(ctors) != 1:
        return "behavior"
    params = ctors[0].get("params", [])
    if {_pascal(p["name"]): p["type"] for p in params} != props:
        # コンストラクタと property が一対一に対応しないデータ型は、代入のしかたが一意に決まらない
        raise ContractError(f"struct {t['name']}: コンストラクタの引数と property が一対一に対応しません"
                            f"（引数 {[p['name'] for p in params]}、property {sorted(props)}）")
    return "data"


class _Names:
    """宣言した型の名前を global:: 付きの完全修飾名にする。property の名前が型名と同じでも曖昧にしない。"""

    def __init__(self, interface):
        self.declared = {t["name"] for t in interface["types"]}

    def q(self, type_text):
        def one(m):
            word = m.group(0)
            if word in self.declared:
                return f"global::{testgen.CORE_NAMESPACE}.{word}"
            return f"global::{word}" if word.startswith("System.") else word
        return _WORD_RE.sub(one, type_text)


def _enum(t):
    return [f"    public enum {t['name']}", "    {", f"        {', '.join(t['values'])}", "    }"]


def _data(t, n):
    name, ctor = t["name"], _members(t, "ctor")[0]
    params = ctor.get("params", [])
    props = [(_pascal(p["name"]), n.q(p["type"])) for p in params]
    sig = ", ".join(f"{n.q(p['type'])} {p['name']}" for p in params)
    out = [f"    public readonly struct {name} : global::System.IEquatable<{name}>", "    {",
           f"        public {name}({sig})", "        {"]
    out += [f"            {prop} = {p['name']};" for (prop, _), p in zip(props, params)]
    out += ["        }", ""]
    out += [f"        public {typ} {prop} {{ get; }}" for prop, typ in props]
    eq = "\n            && ".join(f"global::System.Collections.Generic.EqualityComparer<{typ}>.Default"
                                  f".Equals({prop}, other.{prop})" for prop, typ in props) or "true"
    out += ["", f"        public bool Equals({name} other) =>", f"            {eq};",
            f"        public override bool Equals(object obj) => obj is {name} other && Equals(other);",
            "        public override int GetHashCode()", "        {", "            unchecked", "            {",
            "                int h = 17;"]
    out += [f"                h = h * 31 + global::System.Collections.Generic.EqualityComparer<{typ}>.Default"
            f".GetHashCode({prop});" for prop, typ in props]
    out += ["                return h;", "            }", "        }",
            f"        public static bool operator ==({name} a, {name} b) => a.Equals(b);",
            f"        public static bool operator !=({name} a, {name} b) => !a.Equals(b);",
            "    }"]
    return out


def _interface(t, n):
    out = [f"    public interface I{t['name']}", "    {"]
    for m in t.get("members", []):
        if m.get("static") or m["kind"] not in ("property", "method"):
            continue   # interface に書けないものは探針で縛る
        if m["kind"] == "property":
            out.append(f"        {n.q(m['type'])} {m['name']} {{ get; }}")
        else:
            ps = ", ".join(f"{n.q(p['type'])} {p['name']}" for p in m.get("params", []))
            out.append(f"        {n.q(m['type'])} {m['name']}({ps});")
    out.append("    }")
    return out


def _probe(interface, n):
    """振る舞いの型ごとに、宣言どおりの型で呼ぶだけのメソッド。実行しない。"""
    out = [HEADER, "#nullable disable", f"namespace {PROBE_NAMESPACE}", "{",
           "    // 実行しない。コンパイルが通ることが検査（docs/design/v2_contract_foundry.md §3.3）",
           "    internal static class ContractProbe", "    {",
           "        private static void Is<T>(T value) { }", ""]
    for t in interface["types"]:
        if classify(t) != "behavior":
            continue
        typ = n.q(t["name"])
        args = lambda m: ", ".join(f"default({n.q(p['type'])})" for p in m.get("params", []))  # noqa: E731
        body = [f"            {typ} x = default({typ});",
                f"            Is<global::{testgen.CORE_NAMESPACE}.I{t['name']}>(x);"]
        for m in t.get("members", []):
            owner = typ if m.get("static") or m["kind"] == "const" else "x"
            if m["kind"] == "ctor":
                body.append(f"            Is<{typ}>(new {typ}({args(m)}));")
            elif m["kind"] in ("property", "field", "const"):
                body.append(f"            Is<{n.q(m['type'])}>({owner}.{m['name']});")
            elif m["type"] == "void":
                body.append(f"            {owner}.{m['name']}({args(m)});")
            else:
                body.append(f"            Is<{n.q(m['type'])}>({owner}.{m['name']}({args(m)}));")
        out += [f"        private static void {t['name']}Shape()", "        {"] + body + ["        }", ""]
    out[-1:] = ["    }", "}", ""]
    return "\n".join(out)


def generate(interface, impl_dir, test_dir, existing=(), subdir=CONTRACTS_DIR):
    """{リポジトリからの相対パス: C# の本文}。決定論（同じ入力なら同じバイト列）。

    existing：base に既にあるデータ型の名前。生成しない（同じ名前の型が 2 つになってビルドが通らない）。
    形は探針と性質テストのビルドが確かめる。振る舞いの型は、既にあっても I<型名> を生成する。
    subdir：実装側の置き場（impl_dir の下）。"" なら impl_dir の直下。探針は常に test_dir/Contracts。
    """
    problems = check(interface)
    if problems:
        raise ContractError("interface の形が不正です: " + "; ".join(problems))
    n = _Names(interface)
    files, where = {}, f"{impl_dir}/{subdir}" if subdir else impl_dir
    for t in interface["types"]:
        kind = classify(t)
        if kind != "behavior" and t["name"] in existing:
            continue
        body = _enum(t) if kind == "enum" else _data(t, n) if kind == "data" else _interface(t, n)
        name = t["name"] if kind != "behavior" else "I" + t["name"]
        text = "\n".join([HEADER, "#nullable disable", f"namespace {testgen.CORE_NAMESPACE}", "{"] + body + ["}", ""])
        files[f"{where}/{name}.cs"] = text
    files[f"{test_dir}/{CONTRACTS_DIR}/ContractProbe.cs"] = _probe(interface, n)
    return files


# ============================================================ 参照データ（v2.1c：docs/design/v2_1c_structure_review.md §3 の 1）

REFERENCE_CLASS = "GddReference"
ROT_LABELS = ("0", "R", "2", "L")
_INT_COORD_RE = re.compile(r"\(\s*(-?\d+)\s*,\s*(-?\d+)\s*\)")
_FLOAT_COORD_RE = re.compile(r"\(\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\)")
_PER_RE = re.compile(r"^\s*\d+\s*\S+につき\s*(-?\d+)\s*\S*\s*$")
_INT_RE = re.compile(r"^\s*(-?\d+)(?:\s*\S+)?\s*$")
_SHAPE_RE = re.compile(r"^形状 (\S+) 向き (\S+)$")
_KICK_RE = re.compile(r"^回転補正候補 (\S+) (\S+) → (\S+)$")
_KICK_ALL_RE = re.compile(r"^回転補正候補 (\S+) 全向き遷移$")


def _const_name(pid):
    return pid.replace("-", "_")


def _param_member(pid, name, value, enums, table):
    """構造化仕様 §5 の 1 行 → C# のメンバー（行の列）。読めない値は ContractError（黙って落とさない）。

    table：形・回転補正候補の行。座標が 1 つでも int[][] にする（Shape・Kicks が同じ型で返すため）。
    """
    cid, doc = _const_name(pid), f"        // {pid} {name}"
    m = _INT_RE.match(value) or _PER_RE.match(value)
    if m:
        # 単位（ティック・回・点など）は値の文字列にしか無いので、整数の行だけ注記に残す
        return [f"{doc}：{value}", f"        public const int {cid} = {int(m.group(1))};"]
    rest = _FLOAT_COORD_RE.sub("", value).strip()
    ints, floats = _INT_COORD_RE.findall(value), _FLOAT_COORD_RE.findall(value)
    if floats and not rest:
        if len(ints) == len(floats) and (table or len(ints) > 1):
            cells = ", ".join(f"new[] {{ {x}, {y} }}" for x, y in ints)
            return [doc, f"        public static readonly int[][] {cid} = {{ {cells} }};"]
        if len(ints) == len(floats) == 1:
            return [doc, f"        public static readonly int[] {cid} = {{ {ints[0][0]}, {ints[0][1]} }};"]
        if len(floats) == 1:
            return [doc, f"        public static readonly double[] {cid} = {{ {floats[0][0]}, {floats[0][1]} }};"]
    names = [s.strip() for s in value.split(",")]
    for enum, values in sorted(enums.items()):
        if names and all(n in values for n in names):
            items = ", ".join(f"{enum}.{n}" for n in names)
            return [doc, f"        public static readonly {enum}[] {cid} = {{ {items} }};"]
    raise ContractError(f"参照データ {pid}（{name}）の値を C# にできません: {value!r}")


def _tables(rows, types):
    """形と回転補正候補の行の ID。({型: [向き 0・R・2・L の PR]}, {型: {(from, to): PR}})。欠けていれば ContractError。"""
    rot_of = {lab: i for i, lab in enumerate(ROT_LABELS)}
    shapes, kicks = {t: [None] * 4 for t in types}, {t: {} for t in types}
    for pid, (name, _) in rows.items():
        m, k, k_all = _SHAPE_RE.match(name), _KICK_RE.match(name), _KICK_ALL_RE.match(name)
        if m and m.group(1) in shapes and m.group(2) in rot_of:
            shapes[m.group(1)][rot_of[m.group(2)]] = pid
        elif k and k.group(2) in rot_of and k.group(3) in rot_of:
            for t in k.group(1).split("・"):
                kicks.setdefault(t, {})[(rot_of[k.group(2)], rot_of[k.group(3)])] = pid
        elif k_all:
            for t in k_all.group(1).split("・"):
                for f in range(4):
                    for d in (1, -1):
                        kicks.setdefault(t, {})[(f, (f + d) % 4)] = pid
    missing = [f"形 {t} 向き {ROT_LABELS[r]}" for t in types for r in range(4) if shapes[t][r] is None]
    missing += [f"回転補正候補 {t} {ROT_LABELS[f]} → {ROT_LABELS[(f + d) % 4]}" for t in types for f in range(4)
                for d in (1, -1) if (f, (f + d) % 4) not in kicks.get(t, {})]
    unknown = sorted(set(kicks) - set(types))
    if missing or unknown:
        raise ContractError(f"参照データの表が欠けています: {missing[:5]}、MinoType に無い型: {unknown}")
    return shapes, kicks


def reference_file(rows, enums, impl_dir, subdir=CONTRACTS_DIR):
    """構造化仕様 §5 の参照データを、読み取り専用の C# にする。({相対パス: 本文}, 定数にした PR の ID の列)。

    rows：{PR-xx: (名前, 値)}（propgen.param_rows）。enums：{列挙の名前: 値の列}（MinoType と Rotation が要る。
    Rotation の値の順は向き 0・R・2・L）。
    実装役に参照データを自然言語の表で渡して C# へ写させない（v1 への後退。決定 2・3、L5）。
    行ごとに定数（PR-03 → PR_03）を置き、形と回転補正候補は、その定数を名前で引くメソッド（Shape・Kicks）にする。
    列挙の数値の順には頼らない（base の列挙の宣言順を総監督は見ていない）。値は定数に 1 回だけ書く。
    """
    types, rots = enums["MinoType"], enums["Rotation"]
    shapes, kicks = _tables(rows, types)
    table_ids = {p for ps in shapes.values() for p in ps} | {p for ks in kicks.values() for p in ks.values()}
    out = [HEADER, "#nullable disable", f"namespace {testgen.CORE_NAMESPACE}", "{",
           "    // GDD の参照データ（構造化仕様 §5）。行ごとの定数と、形・回転補正候補を名前で引くメソッド",
           f"    public static class {REFERENCE_CLASS}", "    {"]
    ids = []
    for pid in sorted(rows, key=lambda x: int(x.split("-")[1])):
        name, value = rows[pid]
        out += _param_member(pid, name, value, enums, pid in table_ids)
        ids.append(pid)
    out += ["", "        // 形 type・向き rotation の 4 マスの (x, y)",
            "        public static int[][] Shape(MinoType type, Rotation rotation)", "        {"]
    for t in types:
        for r in range(4):
            out.append(f"            if (type == MinoType.{t} && rotation == Rotation.{rots[r]}) "
                       f"return {_const_name(shapes[t][r])};")
    out += ["            throw new System.ArgumentException(\"unknown shape\");", "        }", "",
            "        // 形 type を向き from から to へ回すときの補正候補 (dx, dy)。試す順",
            "        public static int[][] Kicks(MinoType type, Rotation from, Rotation to)", "        {"]
    groups = {}
    for t in types:
        groups.setdefault(tuple(sorted(kicks[t].items())), []).append(t)
    for table, members in groups.items():
        cond = " || ".join(f"type == MinoType.{t}" for t in members)
        pids = {pid for _, pid in table}
        if len(pids) == 1:
            out.append(f"            if ({cond}) return {_const_name(pids.pop())};")
            continue
        out.append(f"            if ({cond})")
        out.append("            {")
        for (f, to), pid in table:
            out.append(f"                if (from == Rotation.{rots[f]} && to == Rotation.{rots[to]}) "
                       f"return {_const_name(pid)};")
        out.append("            }")
    out += ["            throw new System.ArgumentException(\"unknown kick\");", "        }", "    }", "}", ""]
    where = f"{impl_dir}/{subdir}" if subdir else impl_dir
    return {f"{where}/{REFERENCE_CLASS}.cs": "\n".join(out)}, ids


def lock(files):
    """生成物の sha256。測定器と門は、これと違う生成物を「書き換えられた」とみなす（§3.4）。"""
    return {rel: hashlib.sha256(text.encode("utf-8")).hexdigest() for rel, text in sorted(files.items())}


def implementer_owned(interface):
    """実装役が書く型（振る舞いの型）の名前。データ型は契約の生成物なので、実装役の仕事から外れる。"""
    return [t["name"] for t in interface["types"] if classify(t) == "behavior"]


def load_interface(path):
    """単位定義（interface を持つ）か、interface そのものの JSON を読む。"""
    d = json.loads(Path(path).read_text(encoding="utf-8"))
    return d["interface"] if isinstance(d, dict) and "interface" in d else d


def main(argv=None):
    ap = argparse.ArgumentParser(description="単位定義の interface から、読み取り専用の契約（C#）を作る")
    ap.add_argument("--project", required=True)
    ap.add_argument("--interface", required=True, help="単位定義か interface の JSON")
    ap.add_argument("--out", required=True, help="書き出し先（リポジトリからの相対パスをそのまま下に作る）")
    args = ap.parse_args(argv)
    proj = project.load(args.project)
    try:
        files = generate(load_interface(args.interface), proj["impl_dir"], proj["test_dir"])
    except ContractError as e:
        print(f"NG: {e}")
        return 1
    out = Path(args.out)
    for rel, text in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))
    (out / LOCK_NAME).write_text(json.dumps(lock(files), ensure_ascii=False, indent=2) + "\n",
                                 encoding="utf-8", newline="\n")
    print(f"書き出し: {len(files)} ファイルと {LOCK_NAME}（{out}）")
    return 0


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(exitcode.normalized(main))
