"""実装役に渡すファイルの中身を、ハーネスがプロンプトに埋め込み、細い作業場所に置く。

- 埋め込み（docs/design/v2_1_improvement_plan.md §1.1 の 2）：実装役が自分でファイルを読む手番をなくす。埋め込むのは、
  書き換えてよいファイル（whitelist）、契約の生成物（contractgen が作った読み取り専用のファイル。参照データの
  GddReference を含む）、base の既存の型。総監督は中身を見ない（ハーネスが機械的に埋める）
- 並び（v2.1c §3 の 3）：変わらない前置き（契約・既存の型）を先に、変わるもの（書き換えてよいファイル）を後に置く。
  呼び出しをまたいで前置きの字面が同じになり、キャッシュに乗る
- 仕様書の文章は埋め込まない（v2.1c、2026-09-25 の裁定 1）。v2.1b は単位定義の prompt から正規表現で仕様 ID を拾い、
  構造化仕様の行を抜き出していたが、自然言語で実装役を導くのは v2 の原則に反し、範囲の表記（PR-52〜PR-68）で
  15 行が欠けた。参照データは契約（GddReference）に、規則は性質の宣言（単位定義の prompt）に一元化した
- 上限（MAX_CHARS）を超えたら ContextError。省いて「必要なら読んでください」と書くと、読みに行く手番を促す
"""
import re
from pathlib import Path

CONTRACT_MARKER = "// <auto-generated> contractgen"
MAX_CHARS = 60000
# 参照データの契約のクラス名（contractgen.REFERENCE_CLASS と同じ。重い import を避けて写す。テストで一致を見る）
REFERENCE_CLASS = "GddReference"
# 抜粋でも必ず残す表。形は、ミノを置く・動かすすべてのタスクが使う（性質の文章は PR の ID で形を名指ししない）
ALWAYS_TABLES = ("Shape",)


class ContextError(Exception):
    pass


def contract_files(root, impl_dir):
    """impl_dir の下の、contractgen の生成物（リポジトリからの相対パス）。先頭の行で見分ける。"""
    base = Path(root) / impl_dir
    out = []
    if not base.exists():
        return out
    for p in sorted(base.rglob("*")):
        if not p.is_file() or p.name.endswith(".meta"):
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")[:60]
        except OSError:
            continue
        if head.startswith(CONTRACT_MARKER):
            out.append(p.relative_to(root).as_posix())
    return out


def type_files(root, unit, impl_dir):
    """unit の interface にある型の、base の既存のファイル（impl_dir/<型名><拡張子>）。拡張子は whitelist から取る。

    実装役が既存の型（ActiveMino など）を読みに行く手番をなくす（v2.1b §5 の 1）。
    """
    wl = unit.get("whitelist") or []
    suffix = Path(wl[0]).suffix if wl else ""
    out = []
    for t in (unit.get("interface") or {}).get("types", []):
        rel = f"{impl_dir}/{t['name']}{suffix}"
        if rel not in wl and (Path(root) / rel).exists():
            out.append(rel)
    return out


def readonly_files(root, unit, impl_dir):
    """読み取り専用で見せるもの：契約の生成物と base の既存の型（重複なし、順は決定論）。"""
    out = []
    for rel in contract_files(root, impl_dir) + type_files(root, unit, impl_dir):
        if rel not in out:
            out.append(rel)
    return out


def interface_scope(root, unit, impl_dir):
    """interface のうち、実装役に宣言を描く型の名前（v2.3、N4・F4）。読み取り専用で中身を埋め込む型（契約・既存の型）は
    除く。書き換えてよいファイルの型と、どこにもファイルが無い型は残す。"""
    embedded = {Path(rel).stem for rel in readonly_files(root, unit, impl_dir) if (Path(root) / rel).exists()}
    return {t["name"] for t in (unit.get("interface") or {}).get("types", []) if t["name"] not in embedded}


def visible_files(root, unit, impl_dir):
    """実装役の作業場所に置くもの（= 埋め込むもの）。書き換えてよいファイルと、読み取り専用のもの。"""
    return list(unit.get("whitelist") or []) + readonly_files(root, unit, impl_dir)


def for_unit(root, unit, impl_dir):
    """実装役に渡す前提の全部：契約（参照データを含む）、base の既存の型、書き換えてよいファイル。

    参照データ（GddReference）は、単位定義の prompt が参照する PR と、書き換えてよいファイルがすでに使う定数・表に
    絞った抜粋を埋め込む（v2.2、docs/design/v2_b_efficiency.md §6）。作業場所に置くファイルは全部のまま。
    """
    editable = unit.get("whitelist") or []
    keep = referenced_params(unit.get("prompt"))
    for rel in editable:
        p = Path(root) / rel
        if p.exists():
            keep |= used_reference(p.read_text(encoding="utf-8", errors="replace"))
    return blocks(root, editable, readonly_files(root, unit, impl_dir), keep=keep)


def blocks(root, editable, readonly, keep=None):
    """プロンプトに足す文章。readonly（契約。書き換え不可）を先に、editable（書き換えてよいファイル）を後に置く。

    keep（PR の ID と、表のメソッド名 Shape・Kicks の集合）を渡すと、参照データの契約は抜粋にする（prune_reference）。
    """
    # 作業場所の一覧を先に示す（v2.1d：v2-dry-05c の実装役は、一覧を知るために端末のコマンドを繰り返した）
    present = [rel for rel in list(readonly) + list(editable) if (Path(root) / rel).exists()]
    parts = ["## いまのファイルの中身（ハーネスが埋め込んだもの。作業場所にあるファイルはこれで全部です）",
             "作業場所のファイル一覧：\n" + "\n".join(f"- {rel}" for rel in present)]
    used = 0
    for title, rels in (("読み取り専用（契約。書き換えない）", readonly), ("書き換えてよいファイル", editable)):
        for rel in rels:
            p = Path(root) / rel
            if not p.exists():
                parts.append(f"### {rel}（{title}）\nまだありません。必要なら新しく作ってください。")
                continue
            text = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")
            label = title
            if keep is not None and p.stem == REFERENCE_CLASS:
                pruned = prune_reference(text, keep)
                if pruned != text:
                    text = pruned
                    label += "。この仕事に関わる定数と表の抜粋（作業場所のファイルには全部あります）"
            used += len(text)
            if used > MAX_CHARS:
                raise ContextError(f"埋め込みが上限（{MAX_CHARS} 字）を超えます（{rel} まで {used} 字）")
            parts.append(f"### {rel}（{label}）\n```\n{text.rstrip()}\n```")
    return "\n\n".join(parts)


PARAM_RE = re.compile(r"PR-(\d{2,})(?:\s*(?:〜|～|\.\.|-)\s*PR-(\d{2,}))?")


def referenced_params(text):
    """文章が参照する PR の ID。範囲の表記（PR-52〜PR-68・PR-52..PR-68）は展開する。"""
    ids = set()
    for m in PARAM_RE.finditer(text or ""):
        lo = int(m.group(1))
        hi = int(m.group(2)) if m.group(2) else lo
        ids.update(f"PR-{i:02d}" for i in range(lo, max(lo, hi) + 1))
    return ids


_ENTRY_RE = re.compile(r"^\s*// (PR-\d+)\b")
_METHOD_RE = re.compile(r"^(\s*)public static \S+ (\w+)\(")
_CONST_RE = re.compile(r"\bPR_(\d+)\b")
_USE_RE = re.compile(rf"\b{REFERENCE_CLASS}\.(\w+)")


def used_reference(code):
    """コードがすでに使う参照データ：定数の ID（GddReference.PR_03 → PR-03）と表のメソッド名（Shape・Kicks）。"""
    out = set()
    for name in _USE_RE.findall(code or ""):
        m = re.fullmatch(r"PR_(\d+)", name)
        out.add(f"PR-{m.group(1)}" if m else name)
    return out


def prune_reference(text, keep):
    """参照データの契約（contractgen.reference_file の形）の抜粋（v2.2、docs/design/v2_b_efficiency.md §6）。

    残すもの：keep にある PR の定数、表のメソッドのうち ALWAYS_TABLES・keep に名前があるもの・keep の PR を引くもの、
    残した表が引く定数。外した表は、宣言だけ残して本体を省いた旨を書く。形が読めなければ、そのまま返す。
    v2-smoke-04 では、T1〜T4 は回転補正候補の表（約 1.3 万字の多く）を使わないのに、毎回全部を埋め込んでいた。
    """
    lines = text.splitlines()
    methods = {}  # 名前 → (宣言の注記の行, 終わりの行, 引く PR の ID)
    i = 0
    while i < len(lines):
        m = _METHOD_RE.match(lines[i])
        if not m:
            i += 1
            continue
        end = next((j for j in range(i + 1, len(lines)) if lines[j] == m.group(1) + "}"), None)
        if end is None:
            return text
        start = i - 1 if i > 0 and lines[i - 1].strip().startswith("//") else i
        ids = {f"PR-{n}" for n in _CONST_RE.findall("\n".join(lines[i + 1:end]))}
        methods[m.group(2)] = (start, i, end, ids)
        i = end + 1
    if not any(_ENTRY_RE.match(l) for l in lines):
        return text
    kept = {name for name, (_, _, _, ids) in methods.items()
            if name in ALWAYS_TABLES or name in keep or ids & keep}
    need = set(keep)
    for name in kept:
        need |= methods[name][3]
    out, i = [], 0
    while i < len(lines):
        e = _ENTRY_RE.match(lines[i])
        if e:
            # 定数は「// PR-xx 名前」と宣言の 2 行（contractgen._param_member）
            if e.group(1) in need:
                out += lines[i:i + 2]
            i += 2
            continue
        dropped = next(((name, s, d, end) for name, (s, d, end, _) in methods.items()
                        if s == i and name not in kept), None)
        if dropped:
            name, s, d, end = dropped
            indent = _METHOD_RE.match(lines[d]).group(1)
            out += lines[s:d + 1] + [indent + "{",
                                     indent + f"    // （抜粋では本体を省いた。この仕事の性質は {name} の表の定数を参照しない）",
                                     indent + "}"]
            i = end + 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")
