"""実装役に渡すファイルの中身を、ハーネスがプロンプトに埋め込む（docs/design/v2_1_improvement_plan.md §1.1 の 2）。

実装役が自分でファイルを読む手番をなくす。埋め込むのは、書き換えてよいファイル（whitelist）と、
契約の生成物（contractgen が作った読み取り専用のファイル）の今の中身。総監督は中身を見ない（ハーネスが機械的に埋める）。
"""
from pathlib import Path

CONTRACT_MARKER = "// <auto-generated> contractgen"
MAX_CHARS = 60000


def contract_files(root, impl_dir):
    """impl_dir の下の、contractgen の生成物（リポジトリからの相対パス）。先頭の行で見分ける。"""
    base = Path(root) / impl_dir
    out = []
    if not base.exists():
        return out
    for p in sorted(base.rglob("*")):
        if not p.is_file() or p.name.endswith(".meta"):
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")[:60]
        except OSError:
            continue
        if head.startswith(CONTRACT_MARKER):
            out.append(p.relative_to(root).as_posix())
    return out


def blocks(root, editable, readonly):
    """プロンプトに足す文章。editable は書き換えてよいファイル、readonly は契約（書き換え不可）。"""
    parts = ["## いまのファイルの中身（ハーネスが埋め込んだもの。ファイルを読み直す必要はありません）"]
    used = 0
    for title, rels in (("書き換えてよいファイル", editable), ("読み取り専用（契約。書き換えない）", readonly)):
        for rel in rels:
            p = Path(root) / rel
            if not p.exists():
                parts.append(f"### {rel}（{title}）\nまだありません。必要なら新しく作ってください。")
                continue
            text = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")
            if used + len(text) > MAX_CHARS:
                parts.append(f"### {rel}（{title}）\n大きいので埋め込みを省きました（{len(text)} 字）。必要なら読んでください。")
                continue
            used += len(text)
            parts.append(f"### {rel}（{title}）\n```\n{text.rstrip()}\n```")
    return "\n\n".join(parts)
