"""実装役に渡すファイルの中身を、ハーネスがプロンプトに埋め込む（docs/design/v2_1_improvement_plan.md §1.1 の 2）。

実装役が自分でファイルを読む手番をなくす。埋め込むのは、書き換えてよいファイル（whitelist）と、
契約の生成物（contractgen が作った読み取り専用のファイル）の今の中身。総監督は中身を見ない（ハーネスが機械的に埋める）。
"""
import re
from pathlib import Path

import gdd_check

CONTRACT_MARKER = "// <auto-generated> contractgen"
MAX_CHARS = 60000


def contract_files(root, impl_dir):
    """impl_dir の下の、contractgen の生成物（リポジトリからの相対パス）。先頭の行で見分ける。"""
    base = Path(root) / impl_dir
    out = []
    if not base.exists():
        return out
    for p in sorted(base.rglob("*")):
        if not p.is_file() or p.name.endswith(".meta"):
            continue
        try:
            head = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")[:60]
        except OSError:
            continue
        if head.startswith(CONTRACT_MARKER):
            out.append(p.relative_to(root).as_posix())
    return out


def type_files(root, unit, impl_dir):
    """unit の interface にある型の、base の既存のファイル（impl_dir/<型名><拡張子>）。拡張子は whitelist から取る。

    実装役が既存の型（ActiveMino など）を読みに行く手番をなくす（v2.1b §5 の 1）。
    """
    wl = unit.get("whitelist") or []
    suffix = Path(wl[0]).suffix if wl else ""
    out = []
    for t in (unit.get("interface") or {}).get("types", []):
        rel = f"{impl_dir}/{t['name']}{suffix}"
        if rel not in wl and (Path(root) / rel).exists():
            out.append(rel)
    return out


SPEC_ID_RE = re.compile(r"\b(?:LP|ST|RL|IF|PR)-\d{2,}\b")
ALWAYS_SPEC_IDS = ("LP-07", "LP-08")


def spec_excerpt(spec_text, ids):
    """構造化仕様から、ids の行だけを抜き出す（根拠の行番号は落とす）。無い ID は黙って飛ばす。"""
    problems = []
    _, tables = gdd_check.parse_doc(spec_text, gdd_check.SPEC_META,
                                    [(h, c) for h, _, c in gdd_check.SECTIONS], "spec.md", problems)
    rows = {r["ID"]: r for rs in tables.values() for r in rs}
    lines = []
    for i in sorted(set(ids), key=lambda x: (x.split("-")[0], int(x.split("-")[1]))):
        if i in rows:
            lines.append("- " + " | ".join(str(v) for k, v in rows[i].items() if k not in ("_line", "根拠")))
    return "\n".join(lines)


def for_unit(root, unit, impl_dir, spec_rel=None):
    """実装役に渡す前提の全部：書き換えてよいファイル、契約、base の既存の型、仕様の抜き出し。

    仕様の抜き出しは、単位定義の prompt に出てくる仕様 ID（性質の rule など）と、1 ティックの処理順（LP-07・LP-08）。
    """
    text = blocks(root, unit.get("whitelist") or [],
                  contract_files(root, impl_dir) + type_files(root, unit, impl_dir))
    spec_path = Path(root) / spec_rel if spec_rel else None
    if spec_path is not None and spec_path.exists():
        ids = set(SPEC_ID_RE.findall(unit.get("prompt") or "")) | set(ALWAYS_SPEC_IDS)
        excerpt = spec_excerpt(spec_path.read_text(encoding="utf-8"), ids)
        if excerpt:
            text += "\n\n## 仕様の抜き出し（構造化仕様から。このタスクの性質が引く規則と、1 ティックの処理順）\n\n" + excerpt
    return text


def blocks(root, editable, readonly):
    """プロンプトに足す文章。editable は書き換えてよいファイル、readonly は契約（書き換え不可）。"""
    parts = ["## いまのファイルの中身（ハーネスが埋め込んだもの。ファイルを読み直す必要はありません）"]
    used = 0
    for title, rels in (("書き換えてよいファイル", editable), ("読み取り専用（契約。書き換えない）", readonly)):
        for rel in rels:
            p = Path(root) / rel
            if not p.exists():
                parts.append(f"### {rel}（{title}）\nまだありません。必要なら新しく作ってください。")
                continue
            text = p.read_text(encoding="utf-8", errors="replace").lstrip("﻿")
            if used + len(text) > MAX_CHARS:
                parts.append(f"### {rel}（{title}）\n大きいので埋め込みを省きました（{len(text)} 字）。必要なら読んでください。")
                continue
            used += len(text)
            parts.append(f"### {rel}（{title}）\n```\n{text.rstrip()}\n```")
    return "\n\n".join(parts)
