"""propgen — 性質の宣言から、性質テスト・参照モデル・1 行の反例を機械的に作る（V2-2）。

    python harness/propgen.py --project falling-blocks --decl <properties.json> --interface <契約の JSON> --out <dir>

docs/design/v2_contract_foundry.md §4。Claude が書くのは宣言（JSON）だけで、C# はここが固定テンプレートから作る。
生成物はテストプロジェクトに置き、実装役には読み取り専用（whitelist の外）にする。

**宣言の形**（§4.1）
- `schema: 1`、`gdd_sha256`：宣言を書いたときの GDD の sha256。GDD が変われば生成を拒絶する
- `reference`：参照データの出どころ。`board_width`・`board_height` は PR の ID、`shapes`・`kicks` は
  `"PR-17..PR-51"` の形の範囲。値は構造化仕様 §5 から**名前で**引く（「形状 I 向き 0」「回転補正候補 J・L・S・T・Z 0 → R」）。
  宣言に値を書き写さない（2026-09-17 の前例）
- `start`：`{"phase": "<GamePhase の値>", "locked_max": 整数[, "gap_rows": 0〜4]}`。gap_rows を書くと、下から 0〜gap_rows 行を
  1 マスの穴だけ残して埋める（ライン消去の前提を起こすため。v2r）。書かなければ従来どおり。復元用コンストラクタで、固定ブロックを 0〜locked_max 個
  置いた盤面と、そこに置けるミノから始める
- `steps`・`seeds`：1 本の操作列の長さと、`{"public": 公開シードの本数, "hidden": 非公開シードの本数}`
- `properties`：`{"id": "P-T1-01", "task": "T1", "rule": "RL-16", "given": 式, "then": 式}`

**式**：`before`・`after`（Tick の前後の状態）と `input`（その Tick の TickInput）のメンバー、整数、`true`・`false`・
`null`、列挙の値、`! && || == != < <= > >= + -`、括弧、参照モデルの関数だけを書ける。
関数：`fits(m)`（前の盤面に置けるか）、`in_board(m)`、`moved(m, dx, dy)`、`rotated(m, dir)`、`kick(m, dir)`（SRS の
候補を順に試し、最初に置けた位置。無ければ null）、`drop(m)`（前の盤面で下へ落としきった位置）、
`occupied_before(x, y)`・`occupied_after(x, y)`（盤面外は true）。

**性質の強さ**（§4.2）：タスクごとに、`then` が `==` の性質（結果を一意に決める活性の性質）を 1 つ以上要る。
ランダム系列の中で `given` が 1 回も成り立たなかった性質は、何も検査していないので失敗にする。

**反例**（§4.3）：最初に破れた手で操作列を切り、同じ開始状態から手を 1 つずつ抜いても破れるなら抜く（縮小）。
残った操作列を 1 行で出す。
    PROPERTY_FAIL id=P-T1-01 rule=RL-16 ops=[Right,RotateCw+SoftDrop] expected=ActiveMino.X:4 actual=ActiveMino.X:5
**シード**：公開シードは 1〜public（生成物に書く）。非公開シードは生成物に書かず、測定と門が環境変数
HARNESS_PROPERTY_SEEDS（カンマ区切り）で渡す。無ければ非公開のテストは Ignore になる。
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import exitcode
import gdd_check
import project
import testgen
import unit_schema

SCHEMA = 1
TOP_KEYS = {"schema", "gdd_sha256", "reference", "start", "steps", "seeds", "properties"}
REF_KEYS = {"board_width", "board_height", "shapes", "kicks"}
MAX_STEPS, MAX_PUBLIC, MAX_HIDDEN = 1000, 50, 1000
PROP_ID_RE = re.compile(r"^P-T\d+-\d{2,}$")
TASK_RE = re.compile(r"^T\d+$")
# 性質の出典（rule）：構造化仕様の ID。§3 の規則（RL）に加え、§1 のループ（LP）と §2 の状態遷移（ST）も出典にできる
# （v2r の T10 のゲームオーバーは LP-05・ST-02 などが出典。2026-09-26）。構造化仕様に無い ID は従来どおり落とす
RULE_RE = re.compile(r"^(?:RL|ST|LP)-\d+$")
RANGE_RE = re.compile(r"^PR-(\d+)\.\.PR-(\d+)$")
SHAPE_RE = re.compile(r"^形状 (\S+) 向き (\S+)$")
ORIGIN_RE = re.compile(r"^形状 (\S+) 回転原点$")
KICK_RE = re.compile(r"^回転補正候補 (\S+) (\S+) → (\S+)$")
KICK_ALL_RE = re.compile(r"^回転補正候補 (\S+) 全向き遷移$")
ROT_LABELS = ("0", "R", "2", "L")
HIDDEN_ENV = "HARNESS_PROPERTY_SEEDS"
NAMESPACE = testgen.TEST_NAMESPACE.rsplit(".", 1)[0] + ".Properties"
OUT_DIR = "Properties"
HEADER = "// <auto-generated> propgen が性質の宣言から作った。手で書き換えない。</auto-generated>"
INPUT_ORDER = ("Left", "Right", "RotateCw", "RotateCcw", "SoftDrop", "HardDrop")


class PropertyError(Exception):
    pass


# ============================================================ 契約の読み取り

class Contract:
    """契約の interface から、性質が参照できるものを取り出す。足りなければ PropertyError。"""

    def __init__(self, interface):
        self.types = {t["name"]: t for t in interface["types"]}
        need = [n for n in ("GamePhase", "MinoType", "Rotation", "ActiveMino", "TickInput", "Cell", "GameState")
                if n not in self.types]
        if need:
            raise PropertyError(f"契約に型がありません: {need}（docs/design/v2_contract_foundry.md §3.5）")
        self.enums = {n: t["values"] for n, t in self.types.items() if t["kind"] == "enum"}
        if len(self.enums["Rotation"]) != 4:
            raise PropertyError("Rotation は 4 値の列挙にしてください（向き 0・R・2・L の順）")
        gs = self.types["GameState"]["members"]
        if not any(m["kind"] == "method" and m["name"] == "IsOccupied" and m["type"] == "bool"
                   and [p["type"] for p in m.get("params", [])] == ["int", "int"] for m in gs):
            raise PropertyError("GameState に bool IsOccupied(int x, int y) がありません（§3.5）")
        self.restore = next((m for m in gs if m["kind"] == "ctor" and [p["type"] for p in m.get("params", [])]
                             == ["GamePhase", "ActiveMino?", "System.Collections.Generic.IReadOnlyList<Cell>"]), None)
        if self.restore is None:
            raise PropertyError("GameState に復元用コンストラクタ (GamePhase, ActiveMino?, IReadOnlyList<Cell>) がありません")
        # 状態として読めるもの：列挙・int・bool・ActiveMino・ActiveMino? の property
        self.state = {m["name"]: m["type"] for m in gs if m["kind"] == "property" and not m.get("static")
                      and self._scalar(m["type"])}
        self.mino = {m["name"]: m["type"] for m in self.types["ActiveMino"]["members"] if m["kind"] == "property"}
        self.input = {m["name"]: m["type"] for m in self.types["TickInput"]["members"] if m["kind"] == "property"}
        if sorted(self.input) != sorted(INPUT_ORDER):
            raise PropertyError(f"TickInput の property は {list(INPUT_ORDER)} にしてください")

    def _scalar(self, t):
        return t in ("int", "bool", "ActiveMino", "ActiveMino?") or t in self.enums


# ============================================================ 参照データ（構造化仕様 §5 から名前で引く）

def param_rows(spec_text):
    """{PR-xx: (名前, 値)}。"""
    problems = []
    _, tables = gdd_check.parse_doc(spec_text, gdd_check.SPEC_META,
                                    [(h, c) for h, _, c in gdd_check.SECTIONS], "spec.md", problems)
    rows = {}
    for head, rs in tables.items():
        if head.startswith("## 5."):
            rows.update({r["ID"]: (r["名前"], r["値"]) for r in rs})
    return rows


def _range(text, where):
    m = RANGE_RE.match(str(text))
    if not m or int(m.group(1)) > int(m.group(2)):
        raise PropertyError(f"reference.{where} は \"PR-a..PR-b\" の形にしてください: {text!r}")
    return [f"PR-{i:02d}" for i in range(int(m.group(1)), int(m.group(2)) + 1)]


def _coords(value, n, where):
    cs = [(int(x), int(y)) for x, y in gdd_check.COORD_RE.findall(value)]
    if n is not None and len(cs) != n:
        raise PropertyError(f"{where}: 座標が {n} 個ではありません: {value!r}")
    return cs


def reference(decl_ref, rows, contract):
    """{"width", "height", "shapes": {型: [[(x, y)]*4 （向きの順）]}, "kicks": {型: {(from, to): [(dx, dy)]}}}。"""
    def scalar(key):
        pid = decl_ref[key]
        if pid not in rows:
            raise PropertyError(f"reference.{key}: {pid} が構造化仕様にありません")
        v = unit_schema.resolve_param(rows[pid][1], None)
        if not isinstance(v, int) or v <= 0:
            raise PropertyError(f"reference.{key}: {pid} の値が正の整数ではありません: {rows[pid][1]!r}")
        return v

    types, rot_of = contract.enums["MinoType"], {lab: i for i, lab in enumerate(ROT_LABELS)}
    shapes = {t: [None] * 4 for t in types}
    for pid in _range(decl_ref["shapes"], "shapes"):
        name, value = rows.get(pid, (None, None))
        if name is None:
            raise PropertyError(f"reference.shapes: {pid} が構造化仕様にありません")
        if ORIGIN_RE.match(name):
            continue   # 回転原点は向きごとの形に織り込み済み
        m = SHAPE_RE.match(name)
        if not m or m.group(1) not in shapes or m.group(2) not in rot_of:
            raise PropertyError(f"reference.shapes: {pid} の名前を読めません: {name!r}")
        shapes[m.group(1)][rot_of[m.group(2)]] = _coords(value, 4, pid)
    missing = [f"{t} 向き {ROT_LABELS[r]}" for t in types for r in range(4) if shapes[t][r] is None]
    if missing:
        raise PropertyError(f"reference.shapes: 形がありません: {missing}")

    kicks = {t: {} for t in types}
    for pid in _range(decl_ref["kicks"], "kicks"):
        name, value = rows.get(pid, (None, None))
        if name is None:
            raise PropertyError(f"reference.kicks: {pid} が構造化仕様にありません")
        m, m_all = KICK_RE.match(name), KICK_ALL_RE.match(name)
        if m_all:
            pairs, owners = [(f, (f + d) % 4) for f in range(4) for d in (1, -1)], m_all.group(1).split("・")
        elif m and m.group(2) in rot_of and m.group(3) in rot_of:
            pairs, owners = [(rot_of[m.group(2)], rot_of[m.group(3)])], m.group(1).split("・")
        else:
            raise PropertyError(f"reference.kicks: {pid} の名前を読めません: {name!r}")
        for t in owners:
            if t not in kicks:
                raise PropertyError(f"reference.kicks: {pid} の型 {t} が MinoType にありません")
            for pair in pairs:
                kicks[t][pair] = _coords(value, None, pid)
    missing = [f"{t} {ROT_LABELS[f]} → {ROT_LABELS[(f + d) % 4]}" for t in types for f in range(4) for d in (1, -1)
               if (f, (f + d) % 4) not in kicks[t]]
    if missing:
        raise PropertyError(f"reference.kicks: 候補がありません: {missing[:5]}")
    return {"width": scalar("board_width"), "height": scalar("board_height"), "shapes": shapes, "kicks": kicks}


# ============================================================ 式（字句 → 構文木 → 型検査と C#）

TOKEN_RE = re.compile(r"\s*(?:(\d+)|([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)|(&&|\|\||==|!=|<=|>=|[!<>+\-(),]))")
FUNCS = {  # 名前: (引数の型, 戻りの型, C# の組み立て)
    "fits": (("mino",), "bool", lambda a: f"PropertyModel.Fits(b, {a[0]})"),
    "in_board": (("mino",), "bool", lambda a: f"PropertyModel.InBoard({a[0]})"),
    "moved": (("mino", "int", "int"), "mino", lambda a: f"PropertyModel.Moved({a[0]}, {a[1]}, {a[2]})"),
    "rotated": (("mino", "int"), "mino", lambda a: f"PropertyModel.Rotated({a[0]}, {a[1]})"),
    "kick": (("mino", "int"), "mino?", lambda a: f"PropertyModel.Kick(b, {a[0]}, {a[1]})"),
    "drop": (("mino",), "mino", lambda a: f"PropertyModel.Drop(b, {a[0]})"),
    "occupied_before": (("int", "int"), "bool", lambda a: f"b.Occupied({a[0]}, {a[1]})"),
    "occupied_after": (("int", "int"), "bool", lambda a: f"a.Occupied({a[0]}, {a[1]})"),
}

# 実装役に見せる、式の語彙の定義（v2.3、docs/design/v2_2_architecture_self_critique.md の N2・F3）。FUNCS と同じ名前の
# 集合で、ここが唯一の出どころ。性質が使う関数の意味を、実装役が性質の文面から逆算しなくて済むようにする。
# 単位定義の prompt の門（unit_schema の PROMPT_FORBIDDEN）を通る文字だけで書く。盤面の大きさは参照データの ID で示す
EXPR_VARS = ("- before・after：その Tick の前と後の状態（IGameState）。input：その Tick の TickInput\n"
             "- ミノ m の 4 マス：GddReference.Shape(m.Type, m.Rotation) の各 (x, y) について (m.X + x, m.Y + y)。"
             "y が 1 減る向きが下")
FUNC_DOCS = {
    "fits": "fits(m)：前の盤面で、m の 4 マスがすべて盤面の内側（幅 PR-06、高さ PR-08）にあり、固定ブロックに重ならない",
    "in_board": "in_board(m)：m の 4 マスがすべて盤面の内側にある",
    "moved": "moved(m, dx, dy)：m を x に dx、y に dy だけ動かしたミノ（形と向きは同じ）",
    "rotated": "rotated(m, dir)：m の向きを 1 段回したミノ（位置は同じ）。dir が 1 なら Spawn → Right → Two → Left → Spawn の順に"
               "進め（時計回り）、-1 なら逆に戻す",
    "kick": "kick(m, dir)：rotated(m, dir) に GddReference.Kicks(m.Type, m.Rotation, 回した後の向き) の候補 (dx, dy) を"
            "表の順に足し、前の盤面で最初に fits となるミノ。どれも fits でなければ null",
    "drop": "drop(m)：前の盤面で、m を fits である限り下へ 1 マスずつ動かしきったミノ",
    "occupied_before": "occupied_before(x, y)：前の盤面で (x, y) が固定ブロックか。盤面の外は true",
    "occupied_after": "occupied_after(x, y)：後の盤面で (x, y) が固定ブロックか。盤面の外は true",
}
_CALL_RE = re.compile(r"\b([a-z_]+)\(")


def used_funcs(exprs):
    """式の列が使う関数の名前（FUNCS にあるものだけ。決定論の順）。"""
    names = {n for e in exprs for n in _CALL_RE.findall(e or "")}
    return [n for n in FUNCS if n in names]


def render_vocabulary(exprs):
    """式の列を読むための定義（Markdown）。使う関数だけを並べる。"""
    lines = ["## 性質の式の読み方", "", EXPR_VARS]
    lines += [f"- {FUNC_DOCS[n]}" for n in used_funcs(exprs)]
    return "\n".join(lines)


def tokenize(text, where):
    tokens, pos = [], 0
    while pos < len(text):
        if not text[pos:].strip():
            break
        m = TOKEN_RE.match(text, pos)
        if not m or m.end() == pos:
            raise PropertyError(f"{where}: 読めない字があります: {text[pos:pos + 10]!r}")
        num, name, op = m.groups()
        tokens.append(("int", int(num)) if num else ("name", name) if name else ("op", op))
        pos = m.end()
    return tokens


class _Parser:
    """再帰下降。優先順位は低い順に ||、&&、比較（== != < <= > >=）、+ -、単項（! -）。"""

    def __init__(self, tokens, where):
        self.t, self.i, self.where = tokens, 0, where

    def peek(self):
        return self.t[self.i] if self.i < len(self.t) else (None, None)

    def take(self, op=None):
        tok = self.peek()
        if op is not None and tok != ("op", op):
            raise PropertyError(f"{self.where}: {op!r} が要ります（{tok[1]!r} がありました）")
        self.i += 1
        return tok

    def parse(self):
        e = self.or_()
        if self.i != len(self.t):
            raise PropertyError(f"{self.where}: 式の後ろに余分なものがあります: {self.t[self.i][1]!r}")
        return e

    def binary(self, ops, sub):
        e = sub()
        while self.peek()[0] == "op" and self.peek()[1] in ops:
            op = self.take()[1]
            e = ("bin", op, e, sub())
        return e

    def or_(self):
        return self.binary(("||",), self.and_)

    def and_(self):
        return self.binary(("&&",), self.cmp)

    def cmp(self):
        e = self.add()
        if self.peek()[0] == "op" and self.peek()[1] in ("==", "!=", "<", "<=", ">", ">="):
            op = self.take()[1]
            e = ("bin", op, e, self.add())
        return e

    def add(self):
        return self.binary(("+", "-"), self.unary)

    def unary(self):
        if self.peek() in (("op", "!"), ("op", "-")):
            return ("un", self.take()[1], self.unary())
        return self.primary()

    def primary(self):
        kind, v = self.take()
        if kind == "int":
            return ("int", v)
        if (kind, v) == ("op", "("):
            e = self.or_()
            self.take(")")
            return e
        if kind == "name":
            if self.peek() == ("op", "("):
                self.take("(")
                args = []
                if self.peek() != ("op", ")"):
                    args.append(self.or_())
                    while self.peek() == ("op", ","):
                        self.take(",")
                        args.append(self.or_())
                self.take(")")
                return ("call", v, args)
            return ("name", v)
        raise PropertyError(f"{self.where}: 式が途中で終わっているか、{v!r} を置けない位置です")


def parse(text, where):
    return _Parser(tokenize(text, where), where).parse()


class _Typer:
    """構文木に型を付け、C# にする。型は int・bool・mino・mino?・null・列挙名。"""

    def __init__(self, contract, where):
        self.c, self.where = contract, where

    def err(self, msg):
        raise PropertyError(f"{self.where}: {msg}")

    def ctype(self, t):
        return {"int": "int", "bool": "bool", "mino": "ActiveMino", "mino?": "ActiveMino?"}.get(t, t)

    def of_member(self, t):
        return {"ActiveMino": "mino", "ActiveMino?": "mino?"}.get(t, t)

    def emit(self, e):
        """(C# の式, 型)。"""
        kind = e[0]
        if kind == "int":
            return str(e[1]), "int"
        if kind == "name":
            return self.name(e[1])
        if kind == "call":
            return self.call(e[1], e[2])
        if kind == "un":
            s, t = self.emit(e[2])
            want = "bool" if e[1] == "!" else "int"
            if t != want:
                self.err(f"{e[1]} は {want} にだけ使えます（{t}）")
            return f"({e[1]}{s})", t
        op, (ls, lt), (rs, rt) = e[1], self.emit(e[2]), self.emit(e[3])
        if op in ("&&", "||"):
            if lt != "bool" or rt != "bool":
                self.err(f"{op} の両辺は bool です（{lt}, {rt}）")
            return f"({ls} {op} {rs})", "bool"
        if op in ("+", "-", "<", "<=", ">", ">="):
            if lt != "int" or rt != "int":
                self.err(f"{op} の両辺は int です（{lt}, {rt}）")
            return f"({ls} {op} {rs})", "int" if op in ("+", "-") else "bool"
        return self.equality(op, ls, lt, rs, rt), "bool"

    def comparable(self, lt, rt):
        minos = {"mino", "mino?", "null"}
        if lt in minos and rt in minos:
            return not (lt == "null" and rt == "null") and not ("null" in (lt, rt) and "mino" in (lt, rt))
        return lt == rt

    def equality(self, op, ls, lt, rs, rt):
        if not self.comparable(lt, rt):
            self.err(f"{op} で {lt} と {rt} は比べられません")
        if lt in ("mino", "mino?", "null"):
            s = f"PropertyModel.Same({ls}, {rs})"
            return s if op == "==" else f"(!{s})"
        return f"({ls} {op} {rs})"

    def name(self, n):
        if n in ("true", "false"):
            return n, "bool"
        if n == "null":
            return "null", "null"
        parts = n.split(".")
        if len(parts) == 2 and parts[0] in self.c.enums and parts[1] in self.c.enums[parts[0]]:
            return f"global::{testgen.CORE_NAMESPACE}.{parts[0]}.{parts[1]}", parts[0]
        if len(parts) == 1:
            owners = [en for en, vs in self.c.enums.items() if n in vs]
            if len(owners) == 1:
                return f"global::{testgen.CORE_NAMESPACE}.{owners[0]}.{n}", owners[0]
            if owners:
                self.err(f"{n} は複数の列挙にあります。{owners[0]}.{n} のように書いてください")
        root = {"before": "b", "after": "a", "input": "i"}.get(parts[0])
        if root is None or len(parts) < 2:
            self.err(f"{n!r} は before・after・input のメンバー、列挙の値、true・false・null のどれでもありません")
        table = self.c.input if parts[0] == "input" else self.c.state
        if parts[1] not in table:
            self.err(f"{parts[0]} に {parts[1]} はありません（{sorted(table)}）")
        s, t = f"{root}.{parts[1]}", self.of_member(table[parts[1]])
        for p in parts[2:]:
            if t not in ("mino", "mino?"):
                self.err(f"{n}: {t} にメンバーはありません")
            if p not in self.c.mino:
                self.err(f"{n}: ActiveMino に {p} はありません（{sorted(self.c.mino)}）")
            s = f"PropertyModel.Req({s}).{p}" if t == "mino?" else f"{s}.{p}"
            t = self.of_member(self.c.mino[p])
        return s, t

    def call(self, fn, args):
        if fn not in FUNCS:
            self.err(f"関数 {fn} はありません（{sorted(FUNCS)}）")
        want, ret, build = FUNCS[fn]
        if len(args) != len(want):
            self.err(f"{fn} の引数は {len(want)} 個です")
        out = []
        for a, w in zip(args, want):
            s, t = self.emit(a)
            if w == "mino" and t == "mino?":
                s, t = f"PropertyModel.Req({s})", "mino"
            if t != w:
                self.err(f"{fn} の引数に {t} は渡せません（{w}）")
            out.append(s)
        return build(out), ret


def _strip(text):
    return re.sub(r"\s+", "", text)


def _label(text):
    """反例に出す、左辺の短い名前（after. / before. を落とす）。"""
    return re.sub(r"^(after|before)\.", "", _strip(text)).replace("\"", "'")


def _split_eq(text):
    """then の最上位が「左辺 == 右辺」なら (左辺, 右辺) の文字列。そうでなければ None。

    比較は結合しない（a == b == c は書けない）ので、最上位の == は括弧の外に 1 つだけある。
    """
    tree = parse(text, "then")
    if tree[0] != "bin" or tree[1] != "==":
        return None
    pos, depth = 0, 0
    while pos < len(text):
        m = TOKEN_RE.match(text, pos)
        if not m or m.end() == pos:
            break
        tok = m.group(3)
        depth += (tok == "(") - (tok == ")")
        if tok == "==" and depth == 0:
            return text[:m.start(3)].strip(), text[m.end():].strip()
        pos = m.end()
    return None


# ============================================================ 検査

DIRECTED_BASE, DIRECTED_MAX, DIRECTED_COUNT = 1_000_000_000, 20000, 3
PRE_STATE = ("Phase", "ActiveMino")   # 開始状態で実装を使わずに分かるもの（AtStart）
PRE_FUNCS = {"fits", "in_board", "moved", "rotated", "kick", "drop", "occupied_before"}


def _conjuncts(e):
    if e[0] == "bin" and e[1] == "&&":
        return _conjuncts(e[2]) + _conjuncts(e[3])
    return [e]


def _pre_ok(e):
    """開始状態だけで評価できる式か（before の Phase・ActiveMino、列挙・定数、after を使わない関数だけ）。"""
    kind = e[0]
    if kind == "int":
        return True
    if kind == "name":
        parts = e[1].split(".")
        if parts[0] == "before":
            return len(parts) >= 2 and parts[1] in PRE_STATE
        return parts[0] not in ("after", "input")
    if kind == "call":
        return e[1] in PRE_FUNCS and all(_pre_ok(a) for a in e[2])
    if kind == "un":
        return _pre_ok(e[2])
    return _pre_ok(e[2]) and _pre_ok(e[3])


def _phase_conflict(c, start_phase):
    """`before.Phase == X`（または `!=`）が、開始状態の局面（start.phase）では成り立たないか。

    開始状態はいつも start.phase なので、別の局面を求める前提（例：before.Phase == GameOver）は開始状態では決して成り立たない。
    その局面は系列の途中で起きる（v2r の T10）。これを開始状態の前提に入れると、探索が 0 本になり、実装に依らず
    PROPERTY_UNSATISFIABLE で落ちていた。
    """
    if start_phase is None or c[0] != "bin" or c[1] not in ("==", "!="):
        return False
    sides = [x for x in (c[2], c[3]) if x[0] == "name"]
    if len(sides) != 2 or "before.Phase" not in (sides[0][1], sides[1][1]):
        return False
    value = (sides[1] if sides[0][1] == "before.Phase" else sides[0])[1].split(".")[-1]
    return (value != start_phase) if c[1] == "==" else (value == start_phase)


def directed(p, start_phase=None):
    """前提の探索（v2.1e）の材料：(開始状態で評価する前提の式の列, 最初の手の入力 {名前: bool})。

    given を && で分け、`input.X`・`!input.X` を最初の手に、開始状態だけで評価できるものを前提にする。
    after を使うもの（固定ブロックが増えない、など）は、実装を動かさないと分からないので外す。
    start_phase を渡すと、開始状態の局面と食い違う局面の前提（_phase_conflict）も外す（系列の途中で起きる状態）。
    """
    pre, first = [], {}
    for c in _conjuncts(parse(str(p["given"]), f"{p['id']}.given")):
        lit = c[2] if c[0] == "un" and c[1] == "!" else c
        if lit[0] == "name" and lit[1].startswith("input.") and lit[1].count(".") == 1:
            name, val = lit[1].split(".")[1], c is lit
            if first.get(name, val) != val:
                raise PropertyError(f"{p['id']}.given: input.{name} が真と偽の両方を求めています")
            first[name] = val
        elif _pre_ok(c) and not _phase_conflict(c, start_phase):
            pre.append(c)
    return pre, first


SAMPLING_KEYS = {"start", "quiet", "rate", "count"}
MAX_DIRECTED_COUNT = 10


def sampling(p, rows):
    """前提を狙う抽出（Targeted State Sampling、v2.1f）の材料。(開始状態の制約の式の列, quiet, 千分率, 本数)。

    性質の宣言の任意のキー `sampling`：
    - `start`：開始状態の制約（開始状態だけで評価できる式。`_pre_ok`）。開始状態の分布をこの領域に絞る（拒否抽出）
    - `quiet`：開始から何手、入力を低頻度にするか。整数か `{"param": "PR-xx", "add": n}`（構造化仕様から引く）
    - `rate`：その区間で各キーを押す確率（0〜1）。0 なら無入力
    - `count`：足す系列の本数（1〜10。既定 3）
    固定のように「状態がある区間続いて初めて起きる」希薄な前提を、特定の操作列を書かずに、開始状態の領域と
    入力の分布で起こす。宣言が無ければ ([], 0, 0, 既定の本数)。
    """
    spec = p.get("sampling")
    if spec is None:
        return [], 0, 0, DIRECTED_COUNT
    where = f"{p['id']}.sampling"
    if not isinstance(spec, dict) or not spec.keys() <= SAMPLING_KEYS or "start" not in spec:
        raise PropertyError(f"{where}: キーは start（必須）・quiet・rate・count です")
    start = _conjuncts(parse(str(spec["start"]), f"{where}.start"))
    if not all(_pre_ok(c) for c in start):
        raise PropertyError(f"{where}.start: 開始状態だけで評価できる式にしてください（before の Phase・ActiveMino と、"
                            f"after を使わない関数）")
    q = spec.get("quiet", 0)
    if isinstance(q, dict):
        if set(q) - {"param", "add"} or q.get("param") not in rows:
            raise PropertyError(f"{where}.quiet: {{\"param\": \"PR-xx\", \"add\": 整数}} で構造化仕様にある ID を書いてください")
        base = unit_schema.resolve_param(rows[q["param"]][1], None)
        if not isinstance(base, int):
            raise PropertyError(f"{where}.quiet: {q['param']} の値が整数ではありません")
        q = base + int(q.get("add", 0))
    if isinstance(q, bool) or not isinstance(q, int) or not 0 <= q <= MAX_STEPS:
        raise PropertyError(f"{where}.quiet: 0 以上 {MAX_STEPS} 以下の整数にしてください")
    rate = spec.get("rate", 0)
    if isinstance(rate, bool) or not isinstance(rate, (int, float)) or not 0 <= rate <= 1:
        raise PropertyError(f"{where}.rate: 0 以上 1 以下にしてください")
    count = spec.get("count", DIRECTED_COUNT)
    if isinstance(count, bool) or not isinstance(count, int) or not 1 <= count <= MAX_DIRECTED_COUNT:
        raise PropertyError(f"{where}.count: 1 以上 {MAX_DIRECTED_COUNT} 以下の整数にしてください")
    return start, q, round(rate * 1000), count


def validate(decl, spec_text, gdd_text, interface):
    """問題の一覧（空なら合格）。"""
    if not isinstance(decl, dict):
        return ["宣言がオブジェクトではありません"]
    missing = sorted(TOP_KEYS - decl.keys())
    unknown = sorted(decl.keys() - TOP_KEYS - {k for k in decl if k.startswith("_")})
    if missing or unknown:
        return [f"キーが違います（不足: {missing}、不明: {unknown}）"]
    if decl["schema"] != SCHEMA:
        return [f"schema は {SCHEMA} です"]
    spec_ids, _, spec_problems = unit_schema.spec_index(spec_text, gdd_text)
    if spec_problems:
        return spec_problems
    if decl["gdd_sha256"] != hashlib.sha256(gdd_text.encode("utf-8")).hexdigest():
        return ["gdd_sha256 が今の GDD と一致しません。GDD が変わったので、性質の宣言を見直してから sha256 を更新してください"]
    problems = []
    try:
        contract = Contract(interface)
        ref = decl["reference"]
        if not isinstance(ref, dict) or set(ref) != REF_KEYS:
            raise PropertyError(f"reference のキーは {sorted(REF_KEYS)} です")
        rows = param_rows(spec_text)
        reference(ref, rows, contract)
    except PropertyError as e:
        return [str(e)]

    start = decl["start"]
    if not isinstance(start, dict) or not {"phase", "locked_max"} <= set(start) <= {"phase", "locked_max", "gap_rows"}:
        problems.append("start は {\"phase\", \"locked_max\"}（と任意の \"gap_rows\"）です")
    else:
        if start["phase"] not in contract.enums["GamePhase"]:
            problems.append(f"start.phase は GamePhase の値です: {start['phase']!r}")
        if isinstance(start["locked_max"], bool) or not isinstance(start["locked_max"], int) \
                or not 0 <= start["locked_max"] <= 100:
            problems.append("start.locked_max は 0 以上 100 以下の整数です")
        g = start.get("gap_rows", 0)
        if isinstance(g, bool) or not isinstance(g, int) or not 0 <= g <= 4:
            problems.append("start.gap_rows は 0 以上 4 以下の整数です")
    steps = decl["steps"]
    if isinstance(steps, bool) or not isinstance(steps, int) or not 1 <= steps <= MAX_STEPS:
        problems.append(f"steps は 1 以上 {MAX_STEPS} 以下の整数です")
    seeds = decl["seeds"]
    if not isinstance(seeds, dict) or set(seeds) != {"public", "hidden"} \
            or any(isinstance(v, bool) or not isinstance(v, int) for v in seeds.values()) \
            or not 1 <= seeds["public"] <= MAX_PUBLIC or not 0 <= seeds["hidden"] <= MAX_HIDDEN:
        problems.append(f"seeds は {{\"public\": 1〜{MAX_PUBLIC}, \"hidden\": 0〜{MAX_HIDDEN}}} です")

    props = decl["properties"]
    if not isinstance(props, list) or not props:
        return problems + ["properties は 1 つ以上の性質の列です"]
    ids, live = set(), {}
    for k, p in enumerate(props):
        where = f"properties[{k}]"
        if not isinstance(p, dict) or set(p) - {"_comment", "sampling"} != {"id", "task", "rule", "given", "then"}:
            problems.append(f"{where}: キーは id・task・rule・given・then（と任意の sampling）です")
            continue
        if not PROP_ID_RE.match(str(p["id"])) or p["id"] in ids:
            problems.append(f"{where}: id は P-T<n>-<2 桁以上> で重複しないこと: {p['id']!r}")
        ids.add(p["id"])
        if not TASK_RE.match(str(p["task"])):
            problems.append(f"{where}: task は T<n> です: {p['task']!r}")
        if not RULE_RE.match(str(p["rule"])) or p["rule"] not in spec_ids:
            problems.append(f"{where}: rule は構造化仕様にある ID（RL-xx・ST-xx・LP-xx）です: {p['rule']!r}")
        live.setdefault(p["task"], False)
        for key in ("given", "then"):
            try:
                _, t = _Typer(contract, f"{p['id']}.{key}").emit(parse(str(p[key]), f"{p['id']}.{key}"))
                if t != "bool":
                    problems.append(f"{p['id']}.{key}: 式は bool にしてください（{t}）")
            except PropertyError as e:
                problems.append(str(e))
        try:
            if _split_eq(str(p["then"])) is not None:
                live[p["task"]] = True
        except PropertyError:
            pass
        try:
            directed(p, (decl.get("start") or {}).get("phase") if isinstance(decl.get("start"), dict) else None)
            sampling(p, rows)
        except PropertyError as e:
            problems.append(str(e))
    for task, ok in sorted(live.items()):
        if not ok:
            problems.append(f"{task}: then が == の性質（活性の性質）が 1 つもありません（§4.2）")
    return problems


# ============================================================ 生成

def _cs_coords(cs):
    return "new[] { " + ", ".join(f"new[] {{ {x}, {y} }}" for x, y in cs) + " }"


# 前提の成立回数の行（v2r、docs/design/v2r_protocol.md §8）。report_hits のときだけ出す（V2 の生成物の sha256 を変えない）
HITS_PREFIX = "PROPERTY_HITS "
GAP_CODE = """                // 穴のある行（start.gap_rows）：ライン消去が起きうる開始状態にする。穴のマスは必ず空ける（埋まった行は実際には残らない）
                int gaps = rnd.Next(0, GapRows + 1);
                for (int gy = 0; gy < gaps; gy++)
                {
                    int hole = rnd.Next(PropertyModel.Width);
                    for (int gx = 0; gx < PropertyModel.Width; gx++)
                    {
                        if (gx == hole)
                        {
                            if (occ[gx, gy]) { occ[gx, gy] = false; locked.RemoveAll(c => c.X == gx && c.Y == gy); }
                            continue;
                        }
                        if (occ[gx, gy]) continue;
                        occ[gx, gy] = true;
                        locked.Add(new {ns}.Cell(gx, gy));
                    }
                }
"""
HITS_LINE = ('            global::System.Console.WriteLine("PROPERTY_HITS id=" + id + " rule=" + rule + " given=" + given\n'
             '                + " runs=" + runs.Count);\n')


def _model(ref, contract, start, report_hits=False):
    types = contract.enums["MinoType"]
    shapes = ",\n            ".join("new[] { " + ", ".join(_cs_coords(ref["shapes"][t][r]) for r in range(4)) + " }"
                                    for t in types)
    kick_rows = []
    for t in types:
        per_from = []
        for f in range(4):
            cw, ccw = ref["kicks"][t][(f, (f + 1) % 4)], ref["kicks"][t][(f, (f + 3) % 4)]
            per_from.append(f"new[] {{ {_cs_coords(cw)}, {_cs_coords(ccw)} }}")
        kick_rows.append("new[] { " + ", ".join(per_from) + " }")
    kicks = ",\n            ".join(kick_rows)
    ns = f"global::{testgen.CORE_NAMESPACE}"
    state = contract.state
    fields = "\n".join(f"        public {ns}.{t} {n};" if t.rstrip("?") in contract.types else f"        public {t} {n};"
                       for n, t in state.items())
    copies = "\n".join(f"            o.{n} = s.{n};" for n in state)
    hits_line = HITS_LINE if report_hits else ""
    # start.gap_rows（v2r）：下から 0〜gap_rows 行を、1 マスの穴だけ残して埋める。書かなければ何も出さない（V2 の生成物は同じ）
    gap_const = f"\n        const int GapRows = {start['gap_rows']};" if "gap_rows" in start else ""
    gap_code = GAP_CODE.replace("{ns}", ns) if "gap_rows" in start else ""
    return f"""{HEADER}
// 参照モデル（docs/design/v2_contract_foundry.md §4.1）。値は構造化仕様 §5 から名前で引いた。実装役には見せない。
#nullable disable
using ActiveMino = {ns}.ActiveMino;

namespace {NAMESPACE}
{{
    internal sealed class PropertyNull : global::System.Exception {{ }}

    internal sealed class Snapshot
    {{
{fields}
        public bool[,] Occ;

        public static Snapshot Of({ns}.GameState s)
        {{
            var o = new Snapshot();
{copies}
            o.Occ = new bool[PropertyModel.Width, PropertyModel.Height];
            for (int x = 0; x < PropertyModel.Width; x++)
                for (int y = 0; y < PropertyModel.Height; y++)
                    o.Occ[x, y] = s.IsOccupied(x, y);
            return o;
        }}

        public bool Occupied(int x, int y) => PropertyModel.Occupied(Occ, x, y);
    }}

    internal static class PropertyModel
    {{
        public const int Width = {ref['width']};
        public const int Height = {ref['height']};

        // [MinoType][Rotation][マス] = {{ dx, dy }}
        static readonly int[][][][] Shapes =
        {{
            {shapes}
        }};

        // [MinoType][元の向き][0 = 右回り, 1 = 左回り][候補] = {{ dx, dy }}（SRS。試す順）
        static readonly int[][][][][] Kicks =
        {{
            {kicks}
        }};

        public static ActiveMino Req(ActiveMino? m)
        {{
            if (!m.HasValue) throw new PropertyNull();
            return m.Value;
        }}

        public static bool Same(object x, object y) => global::System.Object.Equals(x, y);

        public static bool Occupied(bool[,] occ, int x, int y) =>
            x < 0 || y < 0 || x >= Width || y >= Height || occ[x, y];

        public static bool InBoard(ActiveMino m)
        {{
            foreach (var c in Shapes[(int)m.Type][(int)m.Rotation])
            {{
                int x = m.X + c[0], y = m.Y + c[1];
                if (x < 0 || y < 0 || x >= Width || y >= Height) return false;
            }}
            return true;
        }}

        public static bool FitsGrid(bool[,] occ, ActiveMino m)
        {{
            foreach (var c in Shapes[(int)m.Type][(int)m.Rotation])
                if (Occupied(occ, m.X + c[0], m.Y + c[1])) return false;
            return true;
        }}

        public static bool Fits(Snapshot b, ActiveMino m) => FitsGrid(b.Occ, m);

        public static ActiveMino Moved(ActiveMino m, int dx, int dy) =>
            new ActiveMino(m.Type, m.X + dx, m.Y + dy, m.Rotation);

        public static ActiveMino Rotated(ActiveMino m, int dir) =>
            new ActiveMino(m.Type, m.X, m.Y, ({ns}.Rotation)((((int)m.Rotation + dir) % 4 + 4) % 4));

        public static ActiveMino? Kick(Snapshot b, ActiveMino m, int dir)
        {{
            if (dir != 1 && dir != -1) return null;
            var r = Rotated(m, dir);
            foreach (var o in Kicks[(int)m.Type][(int)m.Rotation][dir == 1 ? 0 : 1])
            {{
                var c = Moved(r, o[0], o[1]);
                if (Fits(b, c)) return c;
            }}
            return null;
        }}

        public static ActiveMino Drop(Snapshot b, ActiveMino m)
        {{
            var c = m;
            while (Fits(b, Moved(c, 0, -1))) c = Moved(c, 0, -1);
            return c;
        }}

        public static int TypeCount => Shapes.Length;
    }}

    internal static class PropertyRunner
    {{
        public delegate int Check(Snapshot b, {ns}.TickInput i, Snapshot a, out string expected, out string actual);

        const {ns}.GamePhase StartPhase = {ns}.GamePhase.{start['phase']};
        const int LockedMax = {start['locked_max']};{gap_const}
        // 前提の探索（Directed）：公開・非公開のシードと重ならない範囲から、最大 DirectedMax 個を順に試し、
        // 前提が成り立つ系列を DirectedCount 本まで足す
        const int DirectedBase = {DIRECTED_BASE};
        const int DirectedMax = {DIRECTED_MAX};
        const int DirectedCount = {DIRECTED_COUNT};

        public static int[] Public(int n)
        {{
            var s = new int[n];
            for (int k = 0; k < n; k++) s[k] = k + 1;
            return s;
        }}

        public static int[] Hidden()
        {{
            var text = global::System.Environment.GetEnvironmentVariable("{HIDDEN_ENV}");
            if (string.IsNullOrWhiteSpace(text)) global::NUnit.Framework.Assert.Ignore("HIDDEN_SEEDS_ABSENT");
            var parts = text.Split(',');
            var s = new int[parts.Length];
            for (int k = 0; k < parts.Length; k++) s[k] = int.Parse(parts[k].Trim());
            return s;
        }}

        static {ns}.GameState Start(global::System.Random rnd)
        {{
            StartParts(rnd, out var occ, out var locked, out var m);
            return new {ns}.GameState(StartPhase, m, locked);
        }}

        // 開始状態の材料（盤面・固定ブロック・ミノ）。実装を使わない。前提の探索（Directed）も同じ乱数の消費で作る
        static void StartParts(global::System.Random rnd, out bool[,] occOut,
            out global::System.Collections.Generic.List<{ns}.Cell> lockedOut, out ActiveMino mOut)
        {{
            for (int tries = 0; tries < 1000; tries++)
            {{
                var occ = new bool[PropertyModel.Width, PropertyModel.Height];
                var locked = new global::System.Collections.Generic.List<{ns}.Cell>();
                int n = rnd.Next(0, LockedMax + 1);
                for (int k = 0; k < n; k++)
                {{
                    int x = rnd.Next(PropertyModel.Width), y = rnd.Next(PropertyModel.Height / 2);
                    if (occ[x, y]) continue;
                    occ[x, y] = true;
                    locked.Add(new {ns}.Cell(x, y));
                }}
{gap_code}                // 半分は壁際から始める。壁や固定ブロックに当たる操作（移動の拒否・キック）を系列に含めるため
                int mx = rnd.Next(2) == 0
                    ? (rnd.Next(2) == 0 ? rnd.Next(-2, 1) : rnd.Next(PropertyModel.Width - 4, PropertyModel.Width))
                    : rnd.Next(-2, PropertyModel.Width);
                var m = new ActiveMino(({ns}.MinoType)rnd.Next(PropertyModel.TypeCount),
                    mx, rnd.Next(0, PropertyModel.Height), ({ns}.Rotation)rnd.Next(4));
                if (PropertyModel.FitsGrid(occ, m))
                {{
                    occOut = occ; lockedOut = locked; mOut = m;
                    return;
                }}
            }}
            throw new global::System.InvalidOperationException("置ける開始状態を作れませんでした");
        }}

        // 開始状態の Snapshot（実装を使わない）。前提の探索で、開始時点で分かるもの（局面・ミノ・盤面）だけを持つ
        static Snapshot AtStart(bool[,] occ, ActiveMino m)
        {{
            var o = new Snapshot();
            o.Phase = StartPhase;
            o.ActiveMino = m;
            o.Occ = occ;
            return o;
        }}

        public delegate bool Pre(Snapshot b);

        // 前提が最初の手で成り立つ系列を、実装を使わずに決定論で探す（v2.1e：T5 のキックの性質が公開シードで
        // 1 度も前提を満たさず、正しい実装でも VACUOUS になっていた）。開始状態で pre が成り立つシードを探し、
        // 最初の手を first（前提の入力）、残りを乱数の手にする。見つからなければ宣言か生成器の欠陥
        public static global::System.Collections.Generic.List<(int, global::System.Collections.Generic.List<{ns}.TickInput>)>
            Directed(Pre pre, {ns}.TickInput first, int steps, out int searched, int quiet = 0, int ratePerMille = 0,
                int count = DirectedCount)
        {{
            var found = new global::System.Collections.Generic.List<(int, global::System.Collections.Generic.List<{ns}.TickInput>)>();
            searched = 0;
            for (int k = 0; k < DirectedMax && found.Count < count; k++)
            {{
                int seed = DirectedBase + k;
                var rnd = new global::System.Random(seed);
                searched++;
                StartParts(rnd, out var occ, out var locked, out var m);
                bool ok;
                try {{ ok = pre(AtStart(occ, m)); }} catch (PropertyNull) {{ ok = false; }}
                if (!ok) continue;
                // quiet > 0：開始から quiet 手は、各キーを ratePerMille / 1000 の確率でだけ押す（低頻度・無入力の区間）。
                // 希薄な前提（固定など、状態がある区間続いて初めて起きるもの）を起こすための入力の分布（v2.1f）
                var ops = new global::System.Collections.Generic.List<{ns}.TickInput>();
                if (quiet > 0)
                    for (int s = 0; s < quiet && s < steps; s++) ops.Add(RandomInputRate(rnd, ratePerMille));
                else
                    ops.Add(first);
                while (ops.Count < steps) ops.Add(RandomInput(rnd));
                found.Add((seed, ops));
            }}
            return found;
        }}

        static {ns}.TickInput RandomInputRate(global::System.Random rnd, int perMille) =>
            new {ns}.TickInput(rnd.Next(1000) < perMille, rnd.Next(1000) < perMille, rnd.Next(1000) < perMille,
                rnd.Next(1000) < perMille, rnd.Next(1000) < perMille, rnd.Next(1000) < perMille);

        static {ns}.TickInput RandomInput(global::System.Random rnd) =>
            new {ns}.TickInput(rnd.Next(4) == 0, rnd.Next(4) == 0, rnd.Next(4) == 0, rnd.Next(4) == 0,
                rnd.Next(4) == 0, rnd.Next(8) == 0);

        static string Op({ns}.TickInput i)
        {{
            var on = new global::System.Collections.Generic.List<string>();
{chr(10).join(f'            if (i.{n}) on.Add("{n}");' for n in INPUT_ORDER)}
            return on.Count == 0 ? "None" : string.Join("+", on);
        }}

        public static string Fmt(object v)
        {{
            if (v == null) return "null";
            if (v is bool t) return t ? "true" : "false";
            if (v is ActiveMino m) return "(" + m.Type + "," + m.X + "," + m.Y + "," + m.Rotation + ")";
            return v.ToString();
        }}

        // 開始状態（シードで決まる）から ops を順に流し、性質が最初に破れた手の位置を返す（破れなければ -1）。
        // given には前提が成り立った回数を足す
        static int Replay(int seed, global::System.Collections.Generic.List<{ns}.TickInput> ops, Check check,
            ref long given, out string expected, out string actual)
        {{
            var sut = Start(new global::System.Random(seed));
            expected = null; actual = null;
            for (int k = 0; k < ops.Count; k++)
            {{
                var b = Snapshot.Of(sut);
                try {{ sut.Tick(ops[k]); }}
                catch (global::System.Exception e)
                {{
                    expected = "no_exception"; actual = e.GetType().Name;
                    return k;
                }}
                var a = Snapshot.Of(sut);
                int r = check(b, ops[k], a, out expected, out actual);
                if (r != 0) given++;
                if (r == 2) return k;
            }}
            return -1;
        }}

        public static void Run(string id, string rule, int[] seeds, int steps, Check check,
            Pre pre = null, {ns}.TickInput first = default, int quiet = 0, int ratePerMille = 0,
            int count = DirectedCount)
        {{
            long given = 0;
            var runs = new global::System.Collections.Generic.List<(int, global::System.Collections.Generic.List<{ns}.TickInput>)>();
            if (pre != null)
            {{
                // 実装を動かす前に、前提が成り立つ系列があることを確かめる（実装に依らない検査）
                runs.AddRange(Directed(pre, first, steps, out int searched, quiet, ratePerMille, count));
                if (runs.Count == 0)
                    global::NUnit.Framework.Assert.Fail("PROPERTY_UNSATISFIABLE id=" + id + " rule=" + rule
                        + " searched=" + searched);
            }}
            foreach (var seed in seeds)
            {{
                var rnd = new global::System.Random(seed);
                StartParts(rnd, out _, out _, out _);   // 開始状態の分だけ乱数を進める（Replay は同じシードから同じ開始状態を作る）
                var ops = new global::System.Collections.Generic.List<{ns}.TickInput>();
                for (int k = 0; k < steps; k++) ops.Add(RandomInput(rnd));
                runs.Add((seed, ops));
            }}
            foreach (var (seed, ops) in runs)
            {{
                string expected, actual;
                int at = Replay(seed, ops, check, ref given, out expected, out actual);
                if (at >= 0) Shrink(id, rule, seed, ops.GetRange(0, at + 1), check, expected, actual);
            }}
{hits_line}            if (given == 0)
                global::NUnit.Framework.Assert.Fail("PROPERTY_VACUOUS id=" + id + " rule=" + rule + " given=0");
        }}

        // 反例を縮める：手を 1 つ抜いても（同じ開始状態から）性質が破れるなら抜く。抜けなくなるまで繰り返す
        static void Shrink(string id, string rule, int seed, global::System.Collections.Generic.List<{ns}.TickInput> ops,
            Check check, string expected, string actual)
        {{
            long ignored = 0;
            for (bool changed = true; changed;)
            {{
                changed = false;
                for (int j = 0; j < ops.Count && !changed; j++)
                {{
                    var cand = new global::System.Collections.Generic.List<{ns}.TickInput>(ops);
                    cand.RemoveAt(j);
                    string e2, a2;
                    int at = Replay(seed, cand, check, ref ignored, out e2, out a2);
                    if (at >= 0)
                    {{
                        ops = cand.GetRange(0, at + 1);
                        expected = e2; actual = a2; changed = true;
                    }}
                }}
            }}
            var shown = new global::System.Collections.Generic.List<string>();
            foreach (var o in ops) shown.Add(Op(o));
            global::NUnit.Framework.Assert.Fail("PROPERTY_FAIL id=" + id + " rule=" + rule + " ops=["
                + string.Join(",", shown) + "] expected=" + expected + " actual=" + actual);
        }}
    }}
}}
"""


def _check_method(p, contract, rows=None, start_phase=None):
    name = p["id"].replace("-", "_")
    given, _ = _Typer(contract, f"{p['id']}.given").emit(parse(p["given"], f"{p['id']}.given"))
    typer = _Typer(contract, f"{p['id']}.then")
    lines = [f"        public static int {name}(Snapshot b, global::{testgen.CORE_NAMESPACE}.TickInput i, Snapshot a,",
             "            out string expected, out string actual)", "        {",
             "            expected = null; actual = null;", "            bool g;",
             f"            try {{ g = {given}; }} catch (PropertyNull) {{ return 0; }}",
             "            if (!g) return 0;"]
    eq = _split_eq(p["then"])
    if eq is not None:
        (ls, _), (rs, _) = typer.emit(parse(eq[0], p["id"])), typer.emit(parse(eq[1], p["id"]))
        label = _label(eq[0])
        lines += ["            object l, r;",
                  f"            try {{ l = {ls}; }} catch (PropertyNull) {{ l = null; }}",
                  f"            try {{ r = {rs}; }} catch (PropertyNull) {{ r = null; }}",
                  "            if (PropertyModel.Same(l, r)) return 1;",
                  f"            expected = \"{label}:\" + PropertyRunner.Fmt(r);",
                  f"            actual = \"{label}:\" + PropertyRunner.Fmt(l);",
                  "            return 2;"]
    else:
        then, _ = typer.emit(parse(p["then"], p["id"]))
        label = _strip(p["then"]).replace("\"", "'")
        lines += ["            bool t;",
                  f"            try {{ t = {then}; }} catch (PropertyNull) {{ t = false; }}",
                  "            if (t) return 1;",
                  f"            expected = \"{label}:true\";",
                  f"            actual = \"{label}:false\";",
                  "            return 2;"]
    lines.append("        }")
    # 前提の探索（Directed）の材料：開始状態だけで評価する前提と、最初の手
    pre, first = directed(p, start_phase)
    # 抽出の宣言（sampling.start）があれば、開始状態の制約として前提に足す（v2.1f）
    pre = pre + sampling(p, rows or {})[0]
    pre_cs = " && ".join(_Typer(contract, f"{p['id']}.given").emit(c)[0] for c in pre) or "true"
    args = ", ".join("true" if first.get(n) else "false" for n in INPUT_ORDER)
    lines += ["", f"        public static bool Pre_{name}(Snapshot b) => {pre_cs};",
              f"        public static global::{testgen.CORE_NAMESPACE}.TickInput First_{name} =>",
              f"            new global::{testgen.CORE_NAMESPACE}.TickInput({args});"]
    return lines


def _sampling_args(p, rows):
    """Run に渡す抽出の引数（quiet・千分率・本数）。宣言が無ければ空（既定のまま）。"""
    if p.get("sampling") is None:
        return ""
    _, quiet, rate, count = sampling(p, rows or {})
    return f", quiet: {quiet}, ratePerMille: {rate}, count: {count}"


def _tests(task, props, decl, rows=None):
    ns = f"global::{NAMESPACE}"
    out = [HEADER, "#nullable disable", f"namespace {NAMESPACE}", "{",
           "    [global::NUnit.Framework.TestFixture]",
           f"    public sealed class Properties{task}Cases", "    {",
           f"        const int Steps = {decl['steps']};",
           f"        static readonly int[] PublicSeeds = PropertyRunner.Public({decl['seeds']['public']});", ""]
    for p in props:
        name = p["id"].replace("-", "_")
        for suffix, seeds in (("Public", "PublicSeeds"), ("Hidden", "PropertyRunner.Hidden()")):
            out += ["        [global::NUnit.Framework.Test]",
                    f"        [global::NUnit.Framework.Description(\"{p['rule']}\")]",
                    f"        public void {name}_{suffix}() =>",
                    f"            PropertyRunner.Run(\"{p['id']}\", \"{p['rule']}\", {seeds}, Steps, {ns}.Checks.{name},",
                    f"                {ns}.Checks.Pre_{name}, {ns}.Checks.First_{name}{_sampling_args(p, rows)});",
                    ""]
    out[-1:] = ["    }", "}", ""]
    return "\n".join(out)


def generate(decl, spec_text, gdd_text, interface, test_dir, tasks=None, report_hits=False):
    """{リポジトリからの相対パス: C#}。決定論。検査に落ちる宣言は PropertyError。

    report_hits：性質ごとに前提が成り立った回数（given）を標準出力に 1 行（PROPERTY_HITS）出す（v2r §8）。
    測定器は TRX の標準出力から読む（adapters/dotnet.property_hits）。

    tasks：テストのクラスを出すタスク（例 {"T1"}）。None なら全部。参照モデルと判定（Checks.cs）は常に全部出す。
    タスクを積み重ねるとき、まだ実装していないタスクの性質を置くと、それが落ちて受入の判定を汚す。
    """
    problems = validate(decl, spec_text, gdd_text, interface)
    if problems:
        raise PropertyError("性質の宣言が検査を通りません: " + "; ".join(problems[:5]))
    contract = Contract(interface)
    rows = param_rows(spec_text)
    ref = reference(decl["reference"], rows, contract)
    base = f"{test_dir}/{OUT_DIR}"
    files = {f"{base}/PropertyModel.cs": _model(ref, contract, decl["start"], report_hits)}
    checks = [HEADER, "#nullable disable", f"using ActiveMino = global::{testgen.CORE_NAMESPACE}.ActiveMino;", "",
              f"namespace {NAMESPACE}", "{", "    internal static class Checks", "    {"]
    for p in decl["properties"]:
        checks += _check_method(p, contract, rows, decl["start"]["phase"]) + [""]
    checks[-1:] = ["    }", "}", ""]
    files[f"{base}/Checks.cs"] = "\n".join(checks)
    wanted = tasks
    tasks = sorted({p["task"] for p in decl["properties"]}, key=lambda t: int(t[1:]))
    for task in tasks:
        if wanted is not None and task not in wanted:
            continue
        files[f"{base}/Properties{task}Cases.cs"] = _tests(task, [p for p in decl["properties"] if p["task"] == task],
                                                            decl, rows)
    return files


def lock(files):
    return {rel: hashlib.sha256(text.encode("utf-8")).hexdigest() for rel, text in sorted(files.items())}


def main(argv=None):
    ap = argparse.ArgumentParser(description="性質の宣言から、性質テスト・参照モデルを作る")
    ap.add_argument("--project", required=True)
    ap.add_argument("--decl", required=True, help="properties.json")
    ap.add_argument("--interface", required=True, help="契約の interface（単位定義か interface の JSON）")
    ap.add_argument("--out", required=True, help="書き出し先（リポジトリからの相対パスをそのまま下に作る）")
    args = ap.parse_args(argv)
    proj = project.load(args.project)
    cfg = project.config("unit_schema")
    read = unit_schema.git_reader(proj["repo_dir"], f"origin/{proj['base_branch']}", 120)
    iface = json.loads(Path(args.interface).read_text(encoding="utf-8"))
    iface = iface["interface"] if "interface" in iface else iface
    try:
        files = generate(json.loads(Path(args.decl).read_text(encoding="utf-8")),
                         read(cfg["spec_path"]), read(cfg["gdd_path"]), iface, proj["test_dir"])
    except (PropertyError, unit_schema.UnitSchemaError) as e:
        print(f"NG: {e}")
        return 1
    out = Path(args.out)
    for rel, text in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(text.encode("utf-8"))
    (out / "property.lock.json").write_text(json.dumps(lock(files), ensure_ascii=False, indent=2) + "\n",
                                            encoding="utf-8", newline="\n")
    print(f"書き出し: {len(files)} ファイル（{out}）")
    return 0


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(exitcode.normalized(main))
