"""テスト生成器（docs/design/mechanical_barriers.md §3.4・§5 手順 3、ADR-002）。

    python harness/testgen.py --project falling-blocks --unit tools/units/issue_15.json --out <dir>

単位定義 v2 の受入データ（`acceptance.cases`）から、NUnit の C# テストを出力する。
**分解役は C# を 1 行も書かない。** C# の形は、ここにある固定テンプレートだけで決まる。

**決定論**: 同じ単位定義・構造化仕様・GDD からは、同じバイト列を出力する。LLM も乱数も時刻も使わない。
順序は単位定義に書かれた順に従う。

**事前状態（given）の作り方**: 公開 API には状態を書き換える入口がない。そこで given は、引数が
given のフィールドとちょうど一致するコンストラクタ（状態を復元する入口）で作る。そのような
コンストラクタが interface に無い単位は、生成できないとして拒絶する。given が空なら引数なしで作る。

**期待値の出し方**:
- same・±1：操作の前に値を控え、操作の後にそれと比べる。given のリテラルを C# に写さない
- param：構造化仕様 §5 から引いた値をリテラルとして埋め込む
- 自明なリテラル：そのまま埋め込む。列挙のメンバー名は、そのプロパティの型で修飾する

**問い合わせ（query）の行**（手順 5.5）: 戻り値の期待値に加えて、次の 2 つを必ず検査する。
- 冪等：同じ引数で 2 回呼び、2 回目の戻り値が 1 回目と等しい
- 状態の不変（CQS）：呼ぶ前に、対象の型が interface で公開している状態（property / field。
  static な query なら static なもの）をすべて控え、呼んだ後に 1 つずつ等しいことを確かめる

本モジュールは受入データの検査（スキーマ門）を前提にする。門を通っていない単位を渡さないこと。
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import project
import unit_schema

CORE_NAMESPACE = "Game.Core"
TEST_NAMESPACE = "Game.Core.Tests.Generated"
HEADER = ("// <auto-generated>\n"
          "// harness/testgen.py が単位定義 {unit_id}（sha256 {unit_sha}）から出力した。手で編集しない。\n"
          "// </auto-generated>\n")


class GenerationError(Exception):
    pass


def class_name(unit):
    """単位の id から、生成するテストクラスの名前を決める。issue_12 → Issue12Cases"""
    parts = re.split(r"[^A-Za-z0-9]+", unit["id"])
    return "".join(p[:1].upper() + p[1:] for p in parts if p) + "Cases"


def _method_name(case_id):
    return "Case_" + re.sub(r"[^A-Za-z0-9_]", "_", case_id)


def _camel(name):
    return name[:1].lower() + name[1:]


class _Model:
    def __init__(self, unit, params):
        self.params = params
        self.types = {t["name"]: t for t in unit["interface"]["types"]}
        self.members = {}
        for t in unit["interface"]["types"]:
            for m in t.get("members", []):
                self.members[f"{t['name']}.{m['name']}"] = (t, m)

    def is_enum(self, type_name):
        t = self.types.get(type_name.rstrip("?"))
        return bool(t) and t["kind"] == "enum"

    def literal(self, v, type_name, where):
        """値（given・args・期待値のリテラル）を、宣言された型の C# リテラルにする。"""
        base = type_name.rstrip("?")
        if isinstance(v, dict) and "param" in v:
            v = unit_schema.resolve_param(self.params[v["param"]], v.get("index"))
        if v is None:
            return "null"
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, int):
            if base == "uint":
                return f"{v}u"
            if base == "long":
                return f"{v}L"
            if base == "ulong":
                return f"{v}UL"
            return str(v)
        if isinstance(v, str):
            name = v.split(".")[-1]
            if not self.is_enum(base):
                raise GenerationError(f"{where}: 列挙ではない型 {type_name} に {v!r} は書けません")
            if name not in self.types[base]["values"]:
                raise GenerationError(f"{where}: {base} に {name} はありません")
            return f"{base}.{name}"
        raise GenerationError(f"{where}: この値は C# のリテラルにできません: {json.dumps(v, ensure_ascii=False)}")


def _owner_and_member(model, key, where):
    if key not in model.members:
        raise GenerationError(f"{where}: {key} は interface にありません")
    return model.members[key]


def _state_members(model, type_name, static):
    """CQS の検査で控える状態。interface で公開された property / field（const は変わらないので除く）。"""
    t = model.types[type_name]
    return [m for m in t.get("members", [])
            if m["kind"] in ("property", "field") and bool(m.get("static")) == static]


def _query_body(model, case, where):
    op, given, expect = case["op"], case["given"], case["expect"]
    owner, method = _owner_and_member(model, op["query"], where)
    static = bool(method.get("static"))
    t = owner["name"]
    lines = []
    if static:
        if given:
            raise GenerationError(f"{where}: static な query の行は given を持てません")
        target = t
    else:
        fields = []
        for key in given:
            gt, gm = _owner_and_member(model, key, where)
            if gt["name"] != t:
                raise GenerationError(f"{where}: given の {key} は問い合わせ先 {t} の状態ではありません")
            fields.append((gm["name"], gm["type"], given[key]))
        ctor = _require_ctor(model, t, [_camel(n) for n, _, _ in fields], where)
        by_param = {_camel(n): (ty, v) for n, ty, v in fields}
        args = ", ".join(model.literal(by_param[p["name"]][1], by_param[p["name"]][0], f"{where}.given")
                         for p in ctor.get("params", []))
        lines.append(f"var sut = new {t}({args});")
        target = "sut"
    state = _state_members(model, t, static)
    for i, m in enumerate(state):
        # 列は中身を写し取る。参照だけを控えると、その場で書き換えられたときに気づけない
        is_seq = ("<" in m["type"] or m["type"].endswith("[]")) and not m["type"].endswith("?")
        value = f"System.Linq.Enumerable.ToArray({target}.{m['name']})" if is_seq else f"{target}.{m['name']}"
        lines.append(f"var state{i} = {value};")
    call_args = ", ".join(model.literal(op.get("args", {})[p["name"]], p["type"], f"{where}.op.args")
                          for p in method.get("params", []))
    call = f"{target}.{method['name']}({call_args})"
    lines += [f"var first = {call};", f"var second = {call};"]
    ret = expect["return"]
    if ret is None:
        lines.append('Assert.That(first, Is.Null, "return");')
    elif ret == []:
        lines.append('Assert.That(first, Is.Empty, "return");')
    else:
        lines.append(f'Assert.That(first, Is.EqualTo({model.literal(ret, method["type"], where)}), "return");')
    lines.append(f'Assert.That(second, Is.EqualTo(first), "IDEMPOTENT: {op["query"]} を 2 回呼んで戻り値が変わった");')
    for i, m in enumerate(state):
        lines.append(f'Assert.That({target}.{m["name"]}, Is.EqualTo(state{i}), '
                     f'"CQS: {op["query"]} が {t}.{m["name"]} を変えた");')
    return lines


def _case_body(model, case):
    where = f"cases[{case['id']}]"
    lines = []
    op, given, expect = case["op"], case["given"], case["expect"]
    if "query" in op:
        return _query_body(model, case, where)

    if "construct" in op:
        if given:
            raise GenerationError(f"{where}: construct の行は given を持てません（作る前の状態は無い）")
        sut_type = op["construct"]
        _require_ctor(model, sut_type, [], where)
        lines.append(f"var sut = new {sut_type}();")
        act = None
    else:
        owner, method = _owner_and_member(model, op["call"], where)
        sut_type = owner["name"]
        if method.get("static"):
            raise GenerationError(f"{where}: static メソッドの操作は、まだ生成できません: {op['call']}")
        fields = []
        for key in given:
            gt, gm = _owner_and_member(model, key, where)
            if gt["name"] != sut_type:
                raise GenerationError(f"{where}: given の {key} は操作対象 {sut_type} の状態ではありません")
            fields.append((gm["name"], gm["type"], given[key]))
        ctor = _require_ctor(model, sut_type, [_camel(n) for n, _, _ in fields], where)
        by_param = {_camel(n): (t, v) for n, t, v in fields}
        args = ", ".join(model.literal(by_param[p["name"]][1], by_param[p["name"]][0], f"{where}.given")
                         for p in ctor.get("params", []))
        lines.append(f"var sut = new {sut_type}({args});")
        call_args = ", ".join(model.literal(op.get("args", {})[p["name"]], p["type"], f"{where}.op.args")
                              for p in method.get("params", []))
        act = f"sut.{method['name']}({call_args});"

    asserts, captures = [], []
    for i, (key, spec) in enumerate(expect.items()):
        et, em = _owner_and_member(model, key, where)
        static = em.get("static") or em["kind"] == "const"
        if et["name"] != sut_type and not static:
            raise GenerationError(f"{where}: expect の {key} は操作対象 {sut_type} の状態ではありません")
        access = f"{et['name']}.{em['name']}" if static else f"sut.{em['name']}"
        if isinstance(spec, dict) and ("same" in spec or "add" in spec):
            if act is None:
                raise GenerationError(f"{where}: construct の行に same / ±1 は書けません（比べる前の値が無い）")
            if "add" in spec:
                bt, bm = _owner_and_member(model, spec["given"], where)
                base = f"{bt['name']}.{bm['name']}" if (bm.get("static") or bm["kind"] == "const") else f"sut.{bm['name']}"
            else:
                base = access
            captures.append(f"var before{i} = {base};")
            rhs = f"before{i}" if "same" in spec else f"before{i} {'+' if spec['add'] > 0 else '-'} 1"
            asserts.append(f'Assert.That({access}, Is.EqualTo({rhs}), "{key}");')
        elif spec is None:
            asserts.append(f'Assert.That({access}, Is.Null, "{key}");')
        elif spec == []:
            asserts.append(f'Assert.That({access}, Is.Empty, "{key}");')
        else:
            asserts.append(f'Assert.That({access}, Is.EqualTo({model.literal(spec, em["type"], where)}), "{key}");')

    return lines + captures + ([act] if act else []) + asserts


def _require_ctor(model, type_name, param_names, where):
    t = model.types.get(type_name)
    if not t or t["kind"] == "enum":
        raise GenerationError(f"{where}: {type_name} は class / struct として宣言されていません")
    ctors = [m for m in t.get("members", []) if m["kind"] == "ctor"]
    if not ctors and not param_names:
        return {"params": []}
    for c in ctors:
        if sorted(p["name"] for p in c.get("params", [])) == sorted(param_names):
            return c
    want = "引数なし" if not param_names else "引数 " + ", ".join(sorted(param_names))
    raise GenerationError(f"{where}: {type_name} に、{want} のコンストラクタが宣言されていません"
                          "（given を作る入口が無いので生成できません）")


def generate(unit, spec_text, gdd_text, unit_bytes):
    """{ファイル名: C# の本文}。門を通らない単位は GenerationError。"""
    problems = unit_schema.validate(unit, spec_text, gdd_text)
    if problems:
        raise GenerationError("スキーマ門を通らない単位からは生成しません: " + "; ".join(problems[:5]))
    _, params, _ = unit_schema.spec_index(spec_text, gdd_text)
    model = _Model(unit, params)
    name = class_name(unit)
    out = [HEADER.format(unit_id=unit["id"], unit_sha=hashlib.sha256(unit_bytes).hexdigest()[:12]),
           f"using {CORE_NAMESPACE};", "using NUnit.Framework;", "",
           f"namespace {TEST_NAMESPACE}", "{",
           f"    public class {name}", "    {"]
    for case in unit["acceptance"]["cases"]:
        out += ["        [Test]",
                f"        [Description(\"{case['rule']}\")]",
                f"        public void {_method_name(case['id'])}()", "        {"]
        out += [f"            {line}" for line in _case_body(model, case)]
        out += ["        }", ""]
    if out[-1] == "":
        out.pop()
    out += ["    }", "}", ""]
    return {f"{name}.cs": "\n".join(out)}


# ============================================================ 自己テスト用の骨組み

def interface_stub(unit, spec_text, gdd_text):
    """interface から、コンパイルだけが通る骨組みの C# を出す。生成器の自己テスト専用。

    実装役には渡さない。中身は既定値だけで、振る舞いは何も持たない。
    """
    _, params, _ = unit_schema.spec_index(spec_text, gdd_text)
    model = _Model(unit, params)
    out = ["// <auto-generated> testgen の自己テスト用の骨組み。実装ではない。</auto-generated>",
           "#nullable disable", f"namespace {CORE_NAMESPACE}", "{"]
    for t in unit["interface"]["types"]:
        if t["kind"] == "enum":
            out.append(f"    public enum {t['name']} {{ {', '.join(t['values'])} }}")
            continue
        kw = "sealed class" if t["kind"] == "class" else "struct"
        out.append(f"    public {kw} {t['name']}")
        out.append("    {")
        for m in t.get("members", []):
            st = "static " if m.get("static") else ""
            ps = ", ".join(f"{p['type']} {p['name']}" for p in m.get("params", []))
            if m["kind"] == "ctor":
                chain = " : this()" if t["kind"] == "struct" and ps else ""
                out.append(f"        public {t['name']}({ps}){chain} {{ }}")
            elif m["kind"] == "const":
                value = model.literal(m.get("value"), m["type"], f"{t['name']}.{m['name']}")
                out.append(f"        public const {m['type']} {m['name']} = {value};")
            elif m["kind"] == "property":
                out.append(f"        public {st}{m['type']} {m['name']} {{ get; }}")
            elif m["kind"] == "field":
                out.append(f"        public {st}{m['type']} {m['name']};")
            else:
                body = "{ }" if m["type"] == "void" else "=> default;"
                out.append(f"        public {st}{m['type']} {m['name']}({ps}) {body}")
        out.append("    }")
    out += ["}", ""]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description="単位定義 v2 の受入データから NUnit テストを出力する")
    ap.add_argument("--project", required=True)
    ap.add_argument("--unit", required=True)
    ap.add_argument("--out", required=True, help="出力先のディレクトリ")
    args = ap.parse_args(argv)
    proj = project.load(args.project)
    unit_path = Path(args.unit)
    if not unit_path.is_absolute() and not unit_path.exists():
        unit_path = Path(proj["repo_dir"]) / args.unit
    cfg = project.config("unit_schema")
    read = unit_schema.git_reader(proj["repo_dir"], f"origin/{proj['base_branch']}", 120)
    body = unit_path.read_bytes()
    try:
        files = generate(json.loads(body.decode("utf-8")), read(cfg["spec_path"]), read(cfg["gdd_path"]), body)
    except GenerationError as e:
        print(f"NG: {e}")
        return 1
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (out / name).write_bytes(text.encode("utf-8"))
        print(f"出力: {name}")
    return 0


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(main())
